== A Selection from the Journal of David Ferris

When I consider the situation of man in his fallen state,
and the great change that all experience who have been delivered from the power of darkness,
and translated into the kingdom of the dear Son of God; and that,
in order to attain to this happy state,
all must experience a mortification of their natural tempers and evil propensities;
must know the "`old man`" to be slain, and the "`new man`" to be put on, which,
is created according to God in righteousness and true holiness; and that,
in order to walk in the new and living way, we must know old things to pass away,
and all things to become new; I say, when I consider these things,
I feel a concern for my fellow-men, that they may become acquainted with this change.
And apprehending that I have had some acquaintance with it,
by passing through various dispensations of trial and affliction,
I am inclined to leave some account of them to posterity,
in order to show to those who follow, that the Lord is ever near,
and will be found by those who seek Him early;
that He is long-suffering towards those who go astray,
and merciful to all who sincerely turn to Him.
It is my hope that this may minister information and encouragement
to weary travelers in the same road;
and induce them cheerfully to comply with divine requirings.

I wrote a short account of the forepart of my life in Latin,
continued to about the twenty-fifth year of my age.
The many difficulties and dangers in my way,
and doubting whether I should be able hold out to the end,
induced me to keep my history in a language unknown to those around me.
I concluded that if I should hold on my way, I might afterward translate it into English;
and add to it, as I found freedom.
And now, after about twenty years experience of divine support and preservation,
having great cause to say that "`God is good to those
who seek Him,`" that none seek Him in vain,
and that His tender mercies fail not; I am inclined to translate it,
hoping it may be useful, at least to some of my posterity.

I was born at Stratford, in Connecticut, New-England, the 10th day of the third month,
1707.
My parents, Zachariah and Sarah Ferris,
made profession with the people called Presbyterians;
and I had my upbringing in that way.
My father, while I was very young, moved to a place called New Milford.
It being a newly settled place, I had not the advantage of a school; but,
under the care of my mother, I soon learned to read in the Bible,
and understood that there was a Supreme Being, who made all things,
and preserved and upheld them in their order; and that, as the workmanship of His hand,
I stood accountable to Him for every part of my conduct.
About the eighth year of my age, I was informed that the Divine Being was self-existent,
without beginning and without end; and not being able to understand how that could be,
I sometimes thought so intensely on the subject that I became much bewildered.
At length it was shown to me, that the proposition was too high for my comprehension,
and I received something like a reproof for searching into things beyond my capacity.
From that time I was fearful of prying into such deep mysteries.

My mother, being a pious woman,
and much concerned for the good of her offspring (both temporally and
spiritually) was frequent in giving them good advice and admonition;
desiring that we might shun the paths of error; and teaching us, by her own example,
as well as by precept, to walk in the ways of virtue, which lead to peace.
This was a great help to us while young,
and was not easily forgotten when we came to maturity.
Death was a frequent subject of my thoughts; and, in the twelfth year of my age,
I was frequently called by the Holy Spirit to forsake evil, and leave youthful vanities,
which I then delighted in, and to be sober and circumspect in all my ways.
By attention to the divine call, and to the reproofs of instruction daily communicated,
I was preserved from evil; and saw something of the beauty of holiness,
the happy state of the righteous in the world to come,
and the distressing situation of the wicked when they put
off mortality and hear the awful sentence pronounced,
"`Depart, you cursed!`"

About this time, a little circumstance occurred that much affected my mind,
and afforded me lasting instruction.
As I was riding through a river, against a rapid current,
a young dog attempting to swim after me, the stream being too strong for him,
could not keep up with my horse.
He appeared to be in the utmost distress, even to desperation.
As my mind was filled with pity for the poor animal, it was opened to my view,
the awful amazement a poor soul must be in when leaving the world, destitute of hope.
As simple a circumstance as this may appear, it was, I believe, of use to me for years.
I was very careful of my thoughts, words, and actions, for several years afterwards;
the fear of the Lord preserving me from evil.
My mind was humbled under a sense of my daily need of divine help;
and as I abode under a religious concern,
attending to "`the reproofs of instruction which are the way to life,`"^
footnote:[Proverbs 6:23]
an increase of light and life was communicated to me, so that I came to delight in virtue.
As my desires and care for divine things increased, the knowledge of them was unfolded.
I could truly say, the Lord was my delight.
And for some years, as I dwelt in His fear, His yoke was easy, His burden light,
and all childish vanities were burdensome.

While I kept near the Spring of life, with my mind fixed on the true object,
the world and the things thereof lost all their luster.
But, alas, not keeping my eye single to the light, I lost my Leader; and then,
little by little, the world rose again with splendor to my view.
Earthly delights and vanity got such a hold of my affections,
that I took great pleasure in airy and vain company.
This was an unspeakable loss to me,
and I mention it that others may take warning by my ruin.
It seemed almost miraculous that I was ever restored from this lapsed state.
My mother mourned over me, and often advised and urged my return,
showing me the danger of such a course of vanity.
Yet I was not wholly forsaken by my inward Monitor and former Guide.
At times He reproved me, at other times He called me,
wooing and pleading with me to return.
Sometimes, in the midst of my vanity, I saw that I was in the way to death;
and that it would land me in everlasting confusion if I did not forsake it.

Sometimes my concern was so great, that I was obliged to leave my vain companions,
and retire so full of trouble and distress,
that I had no satisfaction until a considerable time afterward.
During these seasons of affliction,
I was ready to promise to forsake my vain course of life,
and to covenant with the Lord that I would do so no more,
provided He would be pleased to grant me His assistance.
But my efforts, being too much in my own strength, proved unavailing.
Vanity so prevailed that I took great delight in music, dancing,
and other vain amusements.

In the twentieth year of my age, I was visited with severe illness; so that I,
and those about me, had very little hope of my recovery.
Then death stared me in the face; and a dreadful scene of woe, anguish,
and misery opened to my view.
It appeared clear to me that if I were then taken off the stage of action,
I should be unavoidably lost;
and that evil spirits were waiting round me to convey my
soul to the mansions of misery and everlasting darkness;
so that my horror, anxiety, and distress were inexpressible.
In the utmost anguish of mind, I cried to the Lord for help;
promising amendment of my ways, if more time and ability were afforded me.
And it pleased a kind Providence to be gracious to me; so that I was restored to health;
and in about a month was able to walk about.

After my recovery I remembered the distress I had been in, and the promise I had made,
when under the dreadful apprehension of everlasting misery and destruction.
I saw the necessity of a faithful performance of my vows.
I was sensible that there was a work to be done;
and that if I did not now comply with my promise, I would have to pass through the same,
or rather a worse scene of misery and distress.
It appeared improbable that a more convenient opportunity
for repentance than the present would be afforded;
and I concluded that this was the time to turn from vanity, forsake my evil ways,
and renounce all my sensual delights.
But, when I had resolved to begin the necessary work of reformation,
the adversary of all good tempted me to believe that it
was now too late to think of obtaining peace with my Maker;
for this plain reason: that, as there was a day or time in which men might be saved; so,
if they let that opportunity pass away unimproved,
it would be in vain to attempt it afterward.
He suggested, that I had had such a day of visitation, and had let it pass by;
that I had been uncommonly favored with help, and had not accepted it;
that I had been made a partaker of the Holy Spirit;
had tasted of the good Word of God and the powers of the world to come,
and had fallen from it;
so now it was impossible that I should again be renewed unto repentance;
seeing I had crucified the Son of God afresh and put Him to open shame.
This reasoning appeared so strong,
and so consonant to the apostle`'s doctrine,
that I gave up the point;
and concluded it was too late to attempt a return with any hope of acceptance.

From that time, during the space of about two months, I never sought for mercy,
but remained in utter despair.
My distress was as great as could well be supported without loss of reason.
I daily wished for death,
desiring that it might occur without laying violent hands on myself,
which I was not much tempted to do.

It was usual with the young people of our neighborhood
to spend much of their time in vanity and merriment,
forgetful of God their Creator,
as if they had been made to please themselves in the gratification of a sensual mind.
And, so long as they were not profanely wicked,
the elderly part of society were not very uneasy with this.
But, in the year 1727,
there was a great reformation at New-Milford among
the young people of the Presbyterian profession.
They had been awakened by the immediate operation of the Holy Spirit on their own minds,
and were brought into great concern for their future well-being,
under which they had no outward assistance.
The apostolic doctrine of "`Christ within,`" and of being "`led by the
Spirit of God,`" was denied by the priest and by many of the people,
who appeared to have little sense of a Divine Teacher in themselves.
These asserted that revelation had now ceased,
and that no such thing was to be experienced in this day.
As I had been the companion of these young people in vanity and dissipation,
they (knowing nothing of my inward condition,
which I had not disclosed to anyone) generally applied to me for counsel and advice.
I was much concerned on their account, being desirous of affording them assistance,
although I had no hope of relief at that time for myself.

My trouble continued and increased, so that I had no satisfaction in life.
On a certain day, in this season of despair and deep distress,
I concluded to leave my native land and go into some foreign country,
where I intended to spend the rest of my days unknown,
that none of my relations or acquaintances would know what had become of me.
Being, in my own apprehension, a poor, lost, reprobate creature,
I was not willing to remain at home to be a disgrace to my relations and countrymen.
This was a day of the deepest affliction and distress that I had known.
Towards evening, as I followed behind the plough, my attention was arrested, as it were,
by a still, small voice, saying:
"`The blood of Jesus Christ His Son cleanses from all sin.`"^
footnote:[1 John 1:7]
But I dismissed it, saying in my heart: "`It is too late;
there has been a day wherein I might have been cleansed; but, alas,
I have let it pass over my head forever!`"

Some time after this, perhaps half an hour later,
while I was pondering what land I should flee to,
the same words passed through my mind again with more authority than before,
and commanded my attention rather more strongly than before.
But I again put them off, concluding I had lost all right to apply such words to myself,
and so resumed the consideration of my flight to a foreign land.
In the meantime my sorrow and anxiety of mind increased,
so that I was not well able to support it, or to go on with my business.
But while I was still pondering, the same words, unsought for and unexpectedly,
passed through my mind with greater power and authority than at any time before:
"`The blood of Jesus Christ His Son cleanses from all sin.`"
This time, at the sound of these words my soul leaped for joy.
I felt that a door of hope was opened, and I said in my heart,
"`If He can cleanse from all sin, why not mine?`"
Then a living hope sprang up in my soul.
I saw that His arms of mercy were open to receive me,
and a way was cleared before me as a road through a thicket.

I was then filled with joy unspeakable.
Thanksgiving and living praises to my Redeemer arose in my heart
for the experience of so great and marvelous a deliverance.
That my feet should be plucked out of the mire, and set upon a rock; and that I,
who just before had no hope,
should now be favored with a well-grounded assurance of pardon and acceptance,
was a mercy never to be forgotten.

I began at this time to seek after divine assistance; and, in infinite kindness,
a hand of help was extended for my restoration and the healing of my backslidings.
I was then enabled to sing upon the banks of deliverance,
and to praise the name of Him who lives forever.
The Holy Spirit, that blessed teacher, whom I had formerly been favored with,
but had forsaken,
was now restored as a leader and teacher to direct
and instruct me in the way to peace and rest.

After such a great favor, my mind was humbled and made subject to the cross of Christ,
and I was whole-heartedly willing to take it up daily,
and follow Him (my kind leader) in the narrow way of self-denial.
And as I was obedient, He led me to forsake the vain course of my life,
and all those youthful delights and sensual pleasures
which were displeasing to my dear Lord and Master;
who in wonderful mercy had lifted me out of the dungeon,
and heard my prayers in a time of deep affliction.
He now became my director in all things, showing me clearly what my duties were,
and enabling me to perform them in an acceptable manner.
But, if at any time I acted in my own will, I lost my strength,
and found no acceptance or benefit by my performances.
By this I gradually learned that I could do nothing acceptably,
without the immediate assistance of the Spirit of Christ the Redeemer.
I thus found a necessity to apply continually to Him--my only and all-sufficient
Helper--and to humbly wait for His assistance and direction;
and as I was faithful, He led me into the path of life, which, if continued in,
will terminate in everlasting peace.

Having gradually learned that nothing of a religious nature could be effectually
done without the immediate assistance of the Holy Spirit,
I may humbly acknowledge that I was wonderfully favored with Divine instruction,
far beyond my expectation, and infinitely above what I deserved.
I was led, as it were, by the hand, and helped over every difficulty that attended me.
But the adversary of my soul tried every stratagem
to draw me aside from the path of virtue.
He strove, night and day, to deter me from walking in this narrow way,
representing the difficulties to be so great that I could never hold out to the end,
and suggesting that all my attempts would be in vain.
He seemed to be continually present, whether I was awake or asleep,
disquieting my mind as much as possible.
But my prayer was incessant for divine aid,
that One stronger than he might appear for my help, and spoil his house.
And, in about a year`'s time,
after I had been raised from the pit of despair (as before related),
I received a promise that "`the God of peace would bruise Satan under my feet shortly.`"^
footnote:[Romans 16:20]
Faith was given to believe in this promise, and I hoped for a speedy deliverance.
But the enemy continued to afflict me with his assaults, temptations,
and evil suggestions for some months afterward.
Notwithstanding which, I still believed the time would come, according to the promise,
and I prayed for its fulfillment in the Lord`'s time.

At length, one stronger than he did indeed come and cast him out,
and wholly dispossessed him; and He not only bruised him under my foot,
but seemed to remove him far from me.
The power of the enemy to assault, or in any way to disquiet me, was then taken away;
nor was he able to lay any temptation before me.
My soul was then daily filled with thanksgiving and living praises for this deliverance,
as well as for the many other manifold mercies and favors
of God that were from day to day bestowed upon me,
who am "`a worm and no man.`"^
footnote:[Ps. 22:6]

To the honor of His great name, who has done marvelous things for me,
and to the praise of His grace, I may say,
that the adversary of all good was not only at this
time thus prevented from troubling me,
but the fountain of divine life was opened,
and the water thereof flowed so freely and plentifully into my soul,
that I was so absorbed in it, and so enamored thereby, that all the riches, honors,
and vain pleasures of this world had no place in my affections.
In this state I longed to be with Christ; which, I could see, was better than to be here.
I do not know that there was one moment, while I was awake,
for the space of nearly two years,
in which I could not sing living praises to Him who lives forever and ever.
No losses, crosses, or disappointments did, in any degree, disturb me at this time;
at least not perceptibly, either to myself or others;
for my delight was in objects very different from
anything this world can give or take away.
I dwelt as upon the mount, out of my enemy`'s reach; and, apparently,
out of danger from any evil.
Here I hoped to remain all the days of my life, desiring that I never should be moved.

However strange this relation may appear to many, I believe it is strictly true.
I am sensible that some who have no experience in things of this nature,
may smile at this narrative;
but others may be glad to find in it a relation of circumstances that
perhaps correspond to their own experience of trials passed through,
or favors received from the divine and all-bountiful hand.
I have no vanity in penning this account; but rather a fear,
lest the succeeding part of my life should not correspond
with the favors conferred upon me by a gracious benefactor,
as stated in the preceding narrative.

While I dwelt as on the mountain, as before related, my spiritual eyes were opened,
and my understanding was enlightened and enlarged.
I then marveled to see that the world, as far as my knowledge of it extended,
was far more in show than in substance, far better in appearance than in reality,
and that even an outward form of godliness was very little to be seen.
I had conceived the opinion that the people among whom I
was educated were better than other professors of Christianity;
but when my eyes were thus anointed to see clearly,
I found very little true religion among them.
Primitive purity appeared to be very much lost,
and I was affected with sorrow and mourning on account of the great
declension among the professors of the Christian religion in general.
For the more I was concerned to examine the subject, and sought for divine wisdom,
the stronger were my convictions, and the clearer my views,
that there had been a general apostasy, and that a life of self-denial,
a dwelling under the cross of Christ, was very little regarded.

Before this period I had had a desire to acquire a knowledge of the languages,
along with other learning,
and now my mind became satisfied that it would be right for me to pursue this course;
but, before I give an account of my progress in this pursuit,
I will recur to a subject that I briefly mentioned before.
It was said that in the year 1727,
some of my companions were brought under a concern for their future happiness.
This concern spread, and so increased among the young people at New-Milford,
that it became a rather general phenomenon.
Many who had spent much of their time in vanity and mirth,
were at this period exercised for their eternal welfare; crying out,
as some did formerly, "`What shall we do to be saved?`"
I think there were nearly sixty of us in about one year,
who joined in close communion with the Presbyterians
in their participation of the bread and wine.
As we were faithful in the discharge of our duty, as far as it was manifested to us,
and endeavored to advance in the path of virtue, our understandings became illuminated,
so as to perceive some things in a different light from that in which they were
seen by our fellow professors--both with respect to practical and doctrinal points.
Sometimes we ventured to mention some of our sentiments upon subjects
where we apprehended there was a difference between us,
which soon involved us in trouble.

We were accused of holding heretical opinions,
and were brought before the church to answer the accusations.
Neighboring ministers were called in to deal with us on this occasion,
but they made little of it.
I had previously stated, in writing, the points of difference between us,
together with various reasons for our dissent;
and when the congregation met to deal with us, I presented it to them.
A committee was thereupon appointed to examine the document,
and to judge whether it would be proper to read it in the assembly.
Upon their returning, the committee reported favorably, and the paper was read before all.
When any difficulty occurred, I was requested to explain my meaning,
which I did accordingly.
After it was read through, they sat silent for some time.
At length, an ancient man arose and said:
"`If this is all wherein our younger brethren are supposed to differ from us,
there is nothing in this writing that I cannot unite with, and say '`Amen`' to.`"
Others, of the foremost rank, expressed the same opinion,
upon which it was concluded that our sentiments were
not so heterodox as to prevent communion with us.
The issue was settled accordingly, and we were pronounced members in full communion.

But, notwithstanding this conclusion,
a report was circulated and generally believed among the people that we were heretics;
and I was considered as a leader among them.
Some called us Quakers, but we knew nothing of that people,
and at that time thought it as bad a name as they did;
though we considered it our duty patiently to bear
the reproach cast upon us for the Truth`'s sake.

But to continue the account of my proceedings relative to the acquisition of learning,
I first went to the teacher in our parish and stayed
with him as a student about one month,
until he refused to teach me any further; alleging, as a reason for his refusal,
that my opinions were too heretical to admit of my reception into the college,
so that my labour would be useless, or at least would not answer the end proposed.
He was a weak man, and had very little experience in religious concerns,
in which I had now acquired a little knowledge; and besides,
he was not scholar enough to teach me to any purpose, which made we willing to leave him.

After this I soon concluded to go to Danby, about thirty miles from my father`'s house,
to place myself under the tuition of a teacher whose name was Moss.
I had heard that he was a good scholar, and a good Christian.
These qualities, I thought, would make the situation pleasant to me,
and I was not disappointed.
But while I was preparing to go to him, I was suddenly taken sick, and became so ill,
that in a few hours it appeared doubtful whether I should recover.
I was in hope that my departure was at hand,
though I did not then see how the Lord would deal with me.

While I was lying very ill, though my understanding was calm and clear,
and my will fully resigned,
my mother came to me and asked me if I thought I should die of that illness.
I answered that I did not know how it might turn out,
but that I should be glad to leave this world if it were the will of God.
After some further discourse, my mother left me alone, and soon after,
my soul (as I apprehended) departed from the body, upon which I was filled with joy,
concluding I had finished with this world and all its troubles.
Being now freed from the shackles of mortality,
I went on rejoicing toward the land of bliss with great alacrity of soul;
and as I departed, I thought I saw my body lying a lifeless lump of matter.
But as I went forward,
I was met by some excellent person whom I took to be the Son of God,
and who informed me that I must not go; saying: "`You must return to the body;
you shall not die, but live, and declare the wonderful works of the Lord.`"
I was troubled to think of returning, to be confined to a body of clay.
However, I stood still, musing and waiting for direction,
when it appeared to be my duty to submit.
I then said, "`The will of the Lord be done,`" and immediately I was in the body.

Soon after this, my mother came again into the room,
and repeated the question that she had put to me before,
whether I thought I should die at that time.
I answered, "`I shall not die of this illness.`"
She seemed surprised that I should answer so positively and without hesitation,
and then queried how I knew it.
"`For,`" said she, "`you told me about an hour ago,
that you did not know whether life or death would be your lot at this time.`"
I then gave her an account of what had just taken place,
which satisfied her respecting my confident answer.
She was filled with joy and thankful acknowledgment to the
Fountain of all Good that I was restored to her,
and that He had been so gracious to me as to reveal
His will in so clear and indubitable a manner.
At this time my mother and I were both Presbyterians,
and continued in that profession for several years after this event.

Being now sensible that my continuance here was required for a longer season,
I became very thoughtful,
lest I had been mistaken in supposing I had obtained the knowledge
of my Divine Master`'s will respecting my learning of languages,
etc. and I was brought into a strict examination whether
I was in the way of my duty in making the attempt.
For, by that time I had come to a clearer sight than I had before concerning human learning,
and how it was insufficient to prepare for the ministry of the Gospel.
Being humbled, and feeling self entirely reduced, I was willing,
if I could discover that my attempt was wrong,
to acknowledge my fault to Him who knows all things,
to repent of my rashness and confess my error,
especially to those to whom I had made known my intentions on the subject.
I had told some of my companions that I saw it to be my duty to acquire learning;
and some considerable time before there was any probability of it,
I had gone so far as to say that I should obtain it.
If, therefore, I had been mistaken, there was now great need of my knowing it,
and making proper acknowledgments on every hand;
as also to be more careful in future not to take anything for granted,
and then report it as a certainty.

During this sickness, which continued about three weeks,
I earnestly desired that I might receive wisdom to
direct me in a way that was acceptable to the Lord.
And although I felt a strong desire for the acquisition of knowledge,
yet I was willing to submit to the disposing hand of Providence,
and I dared not ask for anything but with an entire submission to the Divine will,
knowing very well that if I obtained it in any other disposition,
a blessing would not attend it.
At length, being on the recovery,
and feeling very much exercised in mind on this subject, I had,
one morning as I lay in bed, such a clear manifestation of the Divine will thereupon,
as left no doubts on my mind respecting the course I ought to pursue;
and so I proceeded to prepare for admission into college.

After this time I quickly recovered, and went to the aforementioned teacher at Danby,
of whom I had heard so good a character.
I was well satisfied with him, as I believe he was with me.
He was a religious, tender-spirited man, and I believe was "`a lover of good men,`"^
footnote:[Titus 1:8]
in the apostle`'s sense.
After I had been with him some time, a neighbor, one of his congregation, said to him,
"`I understand you have a heretic with you, preparing for admission into college.`"
He replied, "`I wish that all my congregation were such heretics as he is.`"
To which his neighbor made no reply.
This he told me himself soon after it occurred.
I had stayed with him six months when his other students left him;
and as it did not suit him to attend to me alone, I then went to one Robert Trett,
at New-Milford, and spent about six months with him,
after which time he thought me sufficiently learned for admission into college.
Accordingly I went there, passed an examination in relation to my learning,
and was admitted without any mention of heresy.

After my admission I endeavored to keep humble, and to live in the Lord`'s fear,
so as to be a pattern of lowliness of mind.
I was desirous to be serviceable to mankind,
and endeavored to keep close to that which alone could qualify for it.

Here I think proper to make a remark concerning something in which I was prone to err,
until experience taught me better.
This was, talking too much about religion in my own will and time.
At length I found that this tended to poverty, and I learned, when I was in company,
not to be forward to enter into any discourse concerning religion, or any other subject,
but to be content to keep silence and be esteemed a fool, until Truth arose,
a subject clearly presented, and liberty was given for conversation.
Then I found a qualification given to speak to the edification of others,
and also to my own peace and satisfaction.
I mention this for the benefit of others,
being convinced that many who have had experience of the Truth, and have, in some degree,
witnessed a change of heart,
have talked so much on religious subjects that their souls have become barren,
so as "`scarcely to know when good comes.`"^
footnote:[Jeremiah 17:6]

Now, as I dwelt under a humble sense of my own nothingness,
and sought for the direction of Truth,
I found the Lord to be near by His Spirit to instruct
me in all things necessary to be known;
which were clearly manifested from time to time, as I was able to bear them.

At my entrance into college my principles generally
corresponded with those held by the Presbyterians.
But I now began to think that it was time to examine for myself,
and that I should no longer blindly trust the judgment of my forefathers.
I found it necessary to subject my principles and practices to a strict scrutiny,
because I began to be doubtful concerning some of them.
But I was also convinced that, as a rational creature, simply considered,
I was not at all competent for the undertaking without a Divine Instructor.
I clearly perceived that all right understanding in spiritual concerns
must proceed from the immediate revelation of the Holy Spirit,
and that we could not come to the knowledge of God,
nor of anything relating to His kingdom, without it.

This belief was very different from that held by the people I made profession with,
so that I had no assistance from them.
On the contrary, their conversation, their preaching, and their books,
were against me in this.
I had no outward help but the Bible,
and that I knew I could not understand without Divine assistance.
There were no people with whom I was acquainted who
believed in the Light of Christ within as I did,
so that I had none to look to for instruction in this difficulty, but to Him alone.
But, being very desirous to know the truth in all things,
I cried out to Him whom I believed to be the only Teacher of His people,
and as I waited upon Him for instruction,
my understanding was gradually enlightened so as
to perceive many errors in my former creeds,
and to discover the Truth in opposition to the doctrines of my upbringing.

That which stood most in my way,
and which appeared to be a grievous affliction to mankind,
as well as a great dishonor to a just and righteous God,
was their doctrine of unconditional election and reprobation; which would,
according to their apprehension of it,
shut out the chief part of mankind from all hope of mercy;
for they believed that they were the Lord`'s only people,
and that very few others were within the pale of election (though I believe
there were some amongst them who had a more extensive charity).
I was much concerned on this subject, and being earnestly desirous to discover the truth,
it pleased the Lord to open my understanding so as
to clearly perceive the error of this doctrine;
and I was enabled to believe that Christ, who "`gave Himself a ransom for all,`"^
footnote:[1 Timothy 2:6]
"`desired all men to be saved, and come to the knowledge of the Truth.`"^
footnote:[1 Timothy 2:4]

I rejoiced at this discovery,
and when I was fully convinced of my former error on this subject, I proposed,
for the consideration of one of my fellow students,
whether we had not been mistaken in that point of belief.
We reasoned on the question many times,
until he was almost convinced that we had been in an error on this subject.
He did not then know that my sentiments were different from his own,
but supposed that I had proposed the question only for the sake of argument,
and to hear what could be said for and against it.
I purposely hid my real belief from him,
apprehending it not prudent at that time to expose my genuine sentiments.

By the time we were willing to end the debate on that subject,
I had something new to propose to my friend.
When we were at leisure from our studies, we entered into debate upon this subject;
and so, from time to time, we reasoned the point until we were willing to leave it.
Thus, as things opened to my view,
and my mind became clear in any point of doctrine in opposition to my former belief,
I proposed it for his consideration;
and so we reasoned upon it as long as we thought expedient.
Thus we proceeded from time to time, debating on several points of doctrine,
until my opponent was partly convinced of the truths I advanced,
and also became satisfied that I believed the doctrines
which I had offered for his consideration.
But, as I thought it not a proper time to make my opinions public,
I advised him not to expose them at present, to which he consented.
We spent our leisure time for two or three years in discussing
religious subjects which were new to him,
and I was but recently convinced of the truth of them.

I had before this period heard of a people called Quakers,
but was unacquainted with any of them.
As I had never seen any of their writings, I knew not what doctrines they held,
but can truly ascribe all my knowledge in divine
things to the inward manifestation of grace and truth,
the teaching of the Holy Spirit.
It was Christ, the Light of the world, the Life of men, who opened to me the Scriptures,
and gave me a discerning of their meaning; and,
as I was faithful and obedient to the pointings of Truth,
I was favored with further and clearer discoveries thereof.
In this state I felt desirous that others should come to be acquainted with the Truth,
and I continued to share with my aforementioned fellow
student my views on the various subjects that presented.
We reasoned on them, as they were brought under consideration,
until we had discussed all the principal disputable points of doctrine.
I do not remember that we omitted anything that Robert Barclay
had treated upon in his [.book-title]#Apology for the Christian Divinity,#
although, at that time, I had not seen any of his writings, nor ever heard of them,
as I remember.

I have mentioned these things to show that, according to Christ`'s declaration,
"`If anyone wills to do His will, he shall know concerning the doctrine,
whether it is from God,`"^
footnote:[John 7:17.]
and that "`we need not that any man teach us,
but as the anointing teaches us of all things.`"^
footnote:[1 John 2:27]
And though my friend and I had debated all these points, as before related,
yet at leisure hours we often again discussed them,
and became much of one sentiment on the various subjects,
as will appear when I relate the particulars of our final separation.

By this time I had come to some view of a false ministry and a false worship,
which I saw had been introduced into almost all the churches
of professing Christians with which I was acquainted;
however my sight in these two particulars was not
so clear as it was in many others which we had debated.
Although I perceived a defect in the ministry,
yet I did not then see that it was altogether wrong,
nor did I then know that it was wholly a "`ministry of the letter that kills;`"^
footnote:[2 Corinthians 3:6]
but I afterwards obtained a clearer sight and knowledge thereof.
At this time I thought as a child, and understood as a child,
with regard to these subjects.
And this was also my state respecting divine worship.
I did not clearly perceive that all worship performed in the will of the creature,
and without the immediate assistance of the Holy Spirit,
was truly called "`will-worship`"^
footnote:[Colossians 2:23 KJV]
and idolatry.
But in the process of time I clearly perceived that this was the case.
After our minds were already satisfied on these points,
I first met with Barclay`'s [.book-title]#Apology.#^
footnote:[An [.book-title]#Apology for the True Christian Divinity,#
by Robert Barclay, available on www.friendslibrary.com.]
But I must now leave my classmate and our discussions, and go back a little.

When I had been at college about a year,
the rector sent for me to his house in order to converse with me concerning
some reports that had been circulated of my being a heretic.
After I had, at his request, sat down beside him, he told me he had a desire to hear,
from my own mouth, an account of my state.
He said that it was not from any dissatisfaction in his own mind concerning me,
for he was well-pleased with my conduct since I became one of their members,
that he believed the reports were chiefly owing to misapprehension, ignorance,
and ill-will, and that he wished to know from me the ground of these claims.
This was the substance of his communication.
I replied, that if he would be pleased to have patience with me,
I would give him a plain account,
and would be as brief as possible in order to be intelligible.
I then gave a relation of my first setting out on my religious journey,
of my inward travels, exercises, and experiences to that day,
which took up about an hour and a half, as I supposed.
He was all that time very quiet and attentive, not giving me the least interruption.
I thought he listened with much satisfaction.
When I had concluded we sat silent for some time.
He seemed to be so much affected that he could not easily speak.
After recovering, he at last said: "`Ferris,
I bless God for giving you eyes to see what few see.`"
He said nothing more to me,
except just to inform me that he was well-satisfied with the opportunity,
and so he dismissed me.

I do not know that I concealed from him any of the principles
which I held at the time when I was called a heretic,
but I did not unfold to him all the views which I held at the time I was speaking,
being sensible he could not bear it.
He was a sincere Christian, and a lover of good men,
and afterwards showed a kind regard for me,
saying more in my favor than I apprehend I deserved,
although not more than he believed to be true.
And this was the case with many others whose expectations
of my future usefulness had by some means been raised,
in consequence of which I was much esteemed by the most worthy class of people.
But being kept humble and low in my mind, and seeing my own weakness and infirmities,
I was preserved from the snares of popularity, although they made my trials the greater,
as will appear in the proper place.

After this interview with the rector, I resumed my studies,
which I pursued with diligence,
being desirous to be found in the way of my duty in every respect,
in order that a blessing might accompany my undertaking.
I was careful with my thoughts, words, and actions,
endeavoring to be exemplary and serviceable to all who were about me.

I now became increasingly thoughtful on religious subjects.
The doctrines I had been taught, and the way of worship in which I had been educated,
were subjects of anxious concern.
I was desirous to ascertain whether they would bear up under a strict scrutiny.
Upon trial, I found many of them to be defective,
and from here arose the many debates which I had with my class-mate, as before related.

About the middle of the last year of my residence at the college,
I met with Barclay`'s [.book-title]#Apology;# and after reading it I let my classmate also peruse it,
with whom I had before discussed the doctrines there considered.
He read the work attentively, and made little or no objection to it,
but rather told me that Barclay`'s arguments were unanswerable.
Several other thoughtful students to whom I lent the book, after they had read it,
made the same acknowledgment,
offering very little objection or opposition to the reasoning of its author.

I continued at college until near the time for taking my degrees; and,
being convinced of the errors of my education relating to the doctrines we held,
and the worship we performed,
I apprehended it was time to consider what was best for me to do.
And at last,
having been favored to see that a qualification or commission
derived from man was not sufficient for the gospel ministry,
I concluded not to take their degrees, nor depend upon their authority.

But although I agreed with Barclay on doctrinal subjects,
yet I did not yet know if I could join with the Quakers,
or with any other people with whom I was acquainted.
I still continued a member of the Presbyterian society,
attended their meetings and partaking of their bread and
wine--though I did not feel free to sing with them,
not having been, for some time, in a condition to sing; besides,
it did not appear to be an acceptable sacrifice, or anything like divine worship,
for a mixed multitude to sing of things about which they knew nothing by experience.
My exercise of mind daily increased,
for the time was near at hand when I felt I must leave them.
This was a day of great trial for me.
For, although at the commencement of my religious progress I had forsaken
all the youthful delights and vanities with which I had been amused,
and had been enabled to trample them all under my feet,
expecting never again to encounter such difficulties again,
yet I now found that self was not sufficiently mortified in me.
To be brought down from the pinnacle of honor,
to be esteemed a fool and trampled under foot by high and low, rich and poor,
learned and unlearned, was hard for me to bear.
As I mentioned before, I had been much esteemed; indeed, far more than I deserved.
I knew some people had undue expectations regarding my future usefulness,
and that if I left the college (as I thought it my duty to do) my credit would sink,
and my honors would be laid in the dust.
And then, instead of being caressed and exalted, I would surely be neglected and despised.

But I had other difficulties to encounter as well.
My father looked forward with hope that I should be an honor to him and his family.
He had promised to set me out in the world in the
best manner his circumstances would admit.
I knew that if I were obedient to my convictions of duty,
he would regard it as a disgrace to my family and connections,
and would be more likely to turn me out of his house, than in any way to assist me.
Besides this, I had heard of a vacancy for a minister,
and that the people were waiting for me to occupy it.
The congregation was numerous,
a larger salary was offered than any I knew of in that part of the country,
and I was informed that the rulers of the college had been consulted on this occasion.

Here I knew that if I were to comply with my sense of duty,
I must "`take up the cross`" and head out into the world without provision;
for I had very little property of my own, none to expect from my father,
and no salary to support me.
Many would regard me as the "`off-scouring of all things,`"^
footnote:[1 Corinthians 14:3]
useful for nothing.

I labored under a lively sense of all these difficulties.
Poverty and disgrace stared me in the face; and,
as I had none but the Lord to whom I could make known my distress and discouragement,
nor any other of whom I could ask counsel, I cried out to Him incessantly for wisdom,
strength, and fortitude, that I might be favored with a clear knowledge of my duty,
and be enabled to faithfully obey Him in all things.

At this time my trials and difficulties were so numerous,
that I was ready to conclude with Job that I would "`die in my nest.`"^
footnote:[Job 29:18]
I feared I would never be able to resign all my interest, honor, and credit in the world,
submit to a state of poverty, and incur the disgrace of being a reputed heretic.
These difficulties were presented to my view,
and magnified to a higher degree that any can imagine.
In the height of my distress I entered my closet,
and thus poured out my complaint before the Lord: "`O Lord!
I know not what to do in this day of deep distress and anxiety of soul!
I am not sufficiently clear respecting my duty in
the undertaking and execution of so important a matter.
All that I have in this world that is valuable, and my everlasting happiness also,
seems now to be at stake!`"
Indeed, my present situation appeared so important, that if I were to mistake my course,
and take a wrong direction, all might be lost forever.
And if I were to be led by a spirit of error and confusion,
I might offend my Maker and my fellow creatures, forever remain in a dark wilderness,
and never be restored to favor with God or good men.

Darkness prevailed over me to such an extent at that time,
that I seemed to be placed in the situation of John the Baptist
when he sent two of his disciples to inquire of Christ,
"`Are You the coming One, or should we look for another?`"^
footnote:[Matthew 11:3]
I was almost ready to despair,
and to conclude that I was altogether wrong in proposing to take
a step so contrary to reason as this now appeared to be.
Thus I poured forth my complaint, and mourned before the Lord.
I had none to depend upon but Him,
nor any other of whom I could seek counsel in my distressed circumstances.
My dependance was wholly on Him for wisdom and direction
in this trying and afflicting situation.

It is difficult to conceive, and not in my power to express,
the anxiety of my mind in this proving season;
for everything valuable seemed in danger of being totally lost.
Nevertheless, I cried to the Lord for help, and made covenant with Him,
that if He would be pleased to direct me in the way which would be safe for me to pursue,
manifest His will therein, and afford me assistance to perform my duties,
I would resign all to His disposal, obey His will, no longer reason with flesh and blood,
and put trust in His providence for support and credit in the world,
and for everything else He might think best and most convenient for me.
For I was now clearly convinced,
that if I did not resign everything when it was evidently manifested to be my duty,
I had nothing to expect but death, with regard to my spiritual condition.

While I was thus bemoaning my condition before the Lord and waiting upon Him for direction,
with ardent prayers for His assistance and wisdom to guide me in the right way,
He was graciously pleased to show me that He was
seeking to bring the church out of the wilderness,
or wandering state, in which she had long been destitute of the true Leader.
And He made it clearly known to me that it was His will I should go forth and
be an instrument in His hand for the accomplishment of this design.

Just as soon as I was satisfied on these points, I reasoned not with flesh and blood,
but immediately gave up to the heavenly vision.
I then went to the chief ruler of the college and obtained his permission to go home;
but I told no one my reasons for this procedure.

This was a trying time, for I was about to take an important step.
Like Gideon, I was desirous to "`turn the fleece,`" to wait in retirement for wisdom,
and to carefully consider this weighty undertaking
which now pressed heavily upon my mind.
After staying at home about three weeks,
the will of my Divine Master relating to my removal
from college was satisfactorily manifested to me.
Without making known my purpose,
I returned to the college and settled my affairs in order to leave it.
While I was preparing to depart,
a report was spread among the students that I had
"`turned Quaker,`" and was going to leave them,
yet I did not hear that any of them uttered a harsh or railing word against me.
The rector, Elisha Williams, took an opportunity to converse with me.
He was very moderate, but said he was sorry for my conclusion,
and that heretofore he had entertained a good opinion of me,
with an expectation that I would be useful in my day; but now his hopes were,
in great measure, frustrated.
We had much conversation on the subject,
wherein he signified that he had not given me up for lost.
He appeared serious, and we parted good friends.

As the time for my departure from the college drew near,
being wholly resigned to the Lord`'s will, the cloud was removed from my tabernacle,
my sight was clear, my courage returned,
and the mountains (whose tops so lately appeared to reach
the clouds) were all laid as level as a plain.
Indeed, it felt as if the sea was driven back,
so that there was nothing to interrupt my passage.
I crossed over all as on dry land,
and not a dog was permitted to move its tongue against me.
Then my soul was filled with living praise, thanksgiving, and rejoicing in the Lord,
who had triumphed gloriously.
He was my strength, my song, and my salvation.
The deeps covered my enemies, and they sank to the bottom as a stone.
The right hand of the Lord was glorious in power, and I sang His praises,
for He was worthy, having done great things for me.

Before I left college, I told the rector of my intentions,
and said that I did not know that I would ever return,
but if I should change my mind and wish to take a degree--if it
would be permitted--perhaps I might come back for that purpose;
and if I should conclude not to return,
I would write to him and give the reasons for my conclusion.
He replied that I would be very welcome to a degree,
and that it would give them pleasure to grant me one.

While I was preparing for my journey,
my classmate (before mentioned) being desirous to ride one day with me,
obtained permission from the college,
though the rector warned him that I might instill
bad principles into him and lead him astray.
To this my friend replied,
"`I have lived a great part of the time since I came to the college with him,
and I believe he has done me no harm, but quite the contrary.`"
Then, having bidden them all farewell, we departed.

I thought it a favor that one of my fellow-students who was in good standing,
and esteemed not of the least in the college,
should be willing to take up the cross so far as to accompany me,
who was deemed a heretic or a Quaker.
But feeling a degree of love for me,
it made him fearless of any shame or disgrace that might ensue.

As we rode along, we discussed all the doctrines which we had formerly debated,
and he appeared almost as much convinced of the truth of my sentiments as I was.
Near night, when we were about to separate, he said: "`Ferris,
I believe you are right in leaving the college.
I believe your principles are sound and good; but I do not see, at present,
that I am called to do as you have done.
If, at any time hereafter, I should see it to be my duty to follow your example,
I purpose to have no will of my own, but to submit to and obey the will of my Master.`"
We bade each other farewell, and I saw him no more;
but I afterwards heard that to follow my example was a cross too heavy for him to bear.
He took to preaching for a living among the Presbyterians, and never left them,
to my knowledge.

After I had parted with my companion, I went on to New-Milford,
where my parents and relations resided.
About three weeks afterwards,
I went to a Yearly Meeting of the people called Quakers on Long Island,
in order to discover whether or not they were a living people;
for it was a spiritually living people I desired to find.
I had thought for several years that there must be such a people,
a people who had life in them, and who abounded in love to each other,
as did the primitive Christians;
a people who knew they had passed from death unto life by their love to the brethren.
And there, at the Yearly Meeting,
I was strengthened and even more confirmed that I was right in leaving the college;
for I found a living, humble people, full of love and good works,
such a body of Christians as I had never seen before.
I greatly rejoiced to find what I had been seeking,
and soon acknowledged them to be of the Lord`'s people, and of the true church of Christ,
according to His own description of it, where He said,
"`By this shall all men know that you are My disciples, if you love one another.`"^
footnote:[John 13:35]

I also found that they held and believed the same doctrines which
had been manifested to me immediately by the Holy Spirit;
being the same as those that Robert Barclay had laid down and well defended in his [.book-title]#Apology.#
Before I had read this work,
I did not know there was a people on earth who believed
and lived in the Truth as described by Barclay;
but here I found a numerous society who held the same truths, and lived humble,
self-denying lives, appropriate to the character of Christians.
I was indubitably satisfied that their worship was in spirit and in truth,
and that they were such worshippers as the Father sought and acknowledged.
And I was convinced, beyond a doubt,
that they preached the Gospel in the demonstration of the Spirit;
for divine authority was felt to attend their ministry.
These were not like the scribes to whom I had been listening all my life,
who had neither commission nor authority, except that which was received from man;
being such as the Lord never sent,
and who therefore could not profit the people whom they professed to teach.
I now clearly saw the difference between man-made ministers,
and those whom the Lord qualifies and sends into His harvest field,
the difference between the wheat and the chaff; and truly it was marvelous to me,
to reflect how long I had sat under a formal, dry, and lifeless ministry.

At the meeting before mentioned, there were several eminent ministers from Europe,
both male and female.
There it was that I heard women preach the gospel in the Divine authority of Truth,
far exceeding all the learned rabbis I had known.
This was not so strange to me as it might have been to others, for I had before seen,
by the immediate manifestation of grace and truth, that women, as well as men,
might be clothed with gospel power;
and that daughters as well as sons under the gospel dispensation,
were to have the Spirit poured upon them that they might prophesy.
And though I had never before heard a woman preach,
yet I now rejoiced to see Joel`'s prophecy fulfilled.

After I returned home from the Yearly Meeting,
I wrote a letter to the rector of the college,
informing him that I had determined not to return,
and that I could not with freedom receive any authority
for ministry that a man could give.
I also informed him that, since I left them,
I had heard women preach the gospel far better than any learned man I had ever heard.

Having now left the college,
and separated myself from the people among whom I had been educated,
I saw great cause for thankfulness to the Author of all good,
who had revealed to me the errors of my youth,
the falsity of many doctrines which had been imbibed in my education,
and who had brought me to know His truth and people, so that I had no doubts remaining.
It now became my principal concern to be enabled to walk in the truth,
and experience the Holy Spirit to lead me on my way.

In this state I admired the boundless goodness, the infinite kindness,
and the tender mercy of a gracious God in bringing about my recent deliverance;
especially when I considered how tempestuous were the seas,
and how the billows rolled over me,
how the mountains of opposition raised their lofty heads to stop my passage; and then,
in a short time, how the winds and seas were hushed and made still,
and how the mountains became a perfect plain.
I truly found as great a cause to sing upon the banks
of deliverance as Israel did of old,
after they had passed through the sea on dry ground,
and had turned around to see their enemies lying dead on the shore.
I rejoiced in the Lord and sang praises to Him who had done
marvelous things for me as I submitted to the cross of Christ;
for He had made me acquainted with His blessed truth,
and had at last given me ability to trample the world, with all its riches, honors,
and pleasures, under my feet, though I was accounted a fool by all men.
For these favors I felt myself under great obligations to my gracious Benefactor.

I will now return to a former part of my narrative,
and give some account of my reception by my family
and relatives after returning from college.
After I had parted with my class-mate along the way,
I heard that my father had received intelligence of my intentions,
and was much dissatisfied with my proceedings, saying,
"`If the accounts I have heard are true,
I desire that he never again come into my house.`"
Being informed of this, I went to my brother`'s,
but after some days I went to see my father.
He would not speak to me, but turned and walked away without taking notice of me.
In a few days afterwards I went a second time; but he still refused to speak to me.
After a few more days I went a third time and met him at the door.
I asked about his health, at the same time pulling off my hat;
(for at that time I was not yet convinced of the
necessity of bearing a testimony against hat honor).
He replied he was not very well, and again walked away.
I then went into the house, and upon my father returning,
we sat down and entered into conversation.
He said he had heard I had left college and turned Quaker.
In reply I said that it had been my endeavor for
some years past to follow my divine Leader,
and that I still endeavored to attend to the same Guide,
and to follow wheresoever He might lead me.
I then told him I apprehended that He had led me to leave the college,
and forsake the way of my education,
and that it was possible that the same Guide might at some
point lead me to join with the people called Quakers,
but that, as yet, I knew but little of them.

After some time spent in conversation of this kind,
my father inquired what need there was to forsake the way of my education;
"`For,`" said he, "`the Lord has favored you and been with you in the Presbyterian way,
and if you continue to fear and serve Him in that way, you may do well; and will,
no doubt, end in peace.`"
I answered that it was true I had been much favored under my former religious profession;
for the Lord had been near me, and His living presence with me.
He had led and guided me by His good Spirit,
and had revealed His will to me far beyond anything I had deserved or could have expected;
and that I still desired to follow that Teacher who had never led me astray,
but had brought me, step by step, from one degree of experience to another,
until I was obliged to leave the college and bear a testimony
against the formal religious profession I had made;
and thus He had led me to the present time.

Thus we conversed for some hours,
my father raising various objections against the Quakers and my joining with them.
But, through divine assistance (with which I think I was favored),
I was enabled fully to answer all his objections,
so that he was willing to leave the subject,
and so became moderate and apparently more easy in his mind.
From that time forward, during the remainder of his life,
although he had many opportunities,
he never again entered into any arguments with me on religious subjects,
but was always kind and affectionate.
I thought he concluded that I might still do well in the way he had found me,
and so he remained satisfied.

After I had been some time at home,
new objections arose in my mind against complying
with the customs of those among whom I resided;
customs such as bowing and scraping the foot, putting off the hat and saying,
"`Your servant, sir, madam,
etc.`" and the use of the ungrammatical and corrupt
language of "`you`" to a single person.^
footnote:[Most modern English speakers are unaware that the words "`you`" and
"`your`" were originally _plural_ pronouns used only to address two or more people,
whereas "`thee`" and "`thou`" were used to address one person.
In the 1600`'s,
it became fashionable (as a means of showing honor or flattery) to use
the plural "`you`" or "`your`" in addressing people of higher social status,
while "`thee`" and "`thou`" were reserved for servants, children,
or people of lower social or economic position.
Early Friends felt compelled to stick to what was then considered
"`plain language`" (using thee and thou to every single person,
and you and your to two or more),
rather than showing partiality by addressing certain individuals in the plural.
These may seem like small matters to the 21st century reader,
but many thousands of early Friends were insulted, beaten, imprisoned,
and even hanged for refusing to conform to these outward customs.]
Although in past years, I had known various trials,
and thought I had learned many hard lessons,
yet I now found much within me that still required mortification,
and saw that I had many things yet to learn.
Refusing to the use the plural language in addressing a single person,
although it seemed a small matter, I found very hard to submit to.
I was convinced that the common mode of speaking in the
plural number to a single person was unscriptural,
and also a violation of the rules of grammar.
Indeed, I knew the pride of man had introduced this custom,
yet I also wanted to believe it was not necessary to make myself appear
ridiculous to all around me for a matter of so little importance.
Therefore,
so long as I felt no necessity laid upon me to take up the cross in that respect,
I continued to use the language of my upbringing,
though I used flattering compliments more and more sparingly,
because the disuse of them was not so observable.
However,
it was not long before I found it my duty to say
"`Thee`" and "`Thou`" to every individual person.

Nevertheless,
I found an inclination or temptation in me so to
steer my conversations so as shun this mode of speech;
yet this did not afford peace.
Regardless how small this matter appeared to me,
I could not feel easy without being entirely faithful in every respect;
and when my duty in this particular had been clearly manifested,
I reasoned no longer with flesh and blood, but submitted to the requiring.
It was a rule with me never to do anything of this kind by imitation of other men; but,
whenever anything was required of me, then I was to submit, and so I obtained peace.

About this time,
several students coming from the college invited me to accompany
them on a visit to the minister in our town,
and accordingly I went with them.
We walked with our hats under our arms and so entered the house.
Just as we were about to depart,
I felt it required of me to bear a testimony against the customary hat honor.
So I rose, put on my hat, went to the priest,
and bade him farewell without putting my hand to it, or bowing my body.
This being the first time I had refused these compliments, it was a close trial to me,
and it appeared remarkable that it should be required of me at such a time,
and in such company.
But neither the priest nor any of my companions took notice of it,
so as to make any remark.
My obedience afforded me great peace;
and by yielding to these inward motions of the sure Guide in small things,
I gained strength,
and was more and more confirmed that I was right in making such a change.

I now began to lay aside some of the superfluities of my dress,
and to appear more like a Quaker,
believing it was required of me not to hide myself in any respect,
but to boldly bear testimony to the truth so far as it was clearly manifested to me.
I did not then wonder that people admired at our folly (as they suppose it to be),
in making ourselves a laughing-stock and a by-word by our peculiarity and nonconformity;
for so it appeared to me but a short time before I was obliged to submit to it.
I loved the honor and esteem of men as much as any other,
and would have preferred to enjoy it, if I could have had it along with peace of mind.
But this is not allowed in the school of Christ,
where nothing will do without self-denial and taking up the daily cross.
And if, on our part, there is a full submission in every respect, I can say,
from experience, that our peace will flow as a river.

Having left the college without taking a degree,
I saw it was now probable that I would have no salary to depend on for subsistence.
I had disobliged my father, and of course had nothing to expect from him;
and I had very little of my own to support me.
And now, having come to the twenty-fifth year of my age,
I began to think it necessary to use some endeavors to obtain a livelihood.
I had for several years before this period thought of going to reside in Pennsylvania,
and this prospect now opened so clearly that I was
inclined to believe it was my duty to go there.
I accordingly made ready and went,
in company with three ministering friends from Europe
who were then on a religious visit to America.
We arrived in Philadelphia about the middle of the sixth month, 1733.

Here ends that part of my narrative which was written in my youth in the Latin language.

[.asterism]
'''

[.emphasized]
David Ferris went on to become a faithful and useful minister in the Society of Friends,
often traveling with Samuel Neale and other eminent ministers,
but not before struggling for a very long time with a sense of
insufficiency for the work that the Lord had called him to.
For nearly twenty years,
he felt the Spirit moving him to rise and speak to the Lord`'s
people when they had gathered together for worship,
but, like Moses, he continued to say in his heart,
"`Oh my Lord, who am I that I should speak to Your people.
Please send by the hand of whomever else You may send!`"
But at last,
through the counsel and intercession of that highly-respected
minister of the gospel Comfort Collins,
in the forty-eighth year of his age,
he finally yielded to his call to declare the wonderful works of the Lord.
"`Thus`" he says, "`I was at last lifted out of this horrible pit of my own digging;
and I was so absorbed in the love and mercy of my heavenly Benefactor,
that I was filled with thankfulness and praise, attended with a desire that,
in the future, I might diligently watch and wait for the pointing of His holy finger,
to every service He might be pleased to allot me;
that henceforth no opportunity might be lost of manifesting my gratitude,
by obedience to His will.`"
He departed this life, the 5th of the twelfth month, 1779,
aged upwards of seventy-two years,
having been an effectual minister about twenty-four years.
