== Chapter V.

[.chapter-synopsis]
* He is acknowledged a minister in 1758, and goes out with Certificate
* He unites in further service with Samuel Neale, and with Robert Valentine when the latter was young in the ministry
* Close trial from a false report of his property being destroyed
* His concern for slaves in North Carolina and Virginia
* He again visits New England
* His concluding remarks in 1779, about seven months before his decease

In the year 1758, I was received into the meeting of ministers and elders,
and soon after obtained a certificate to visit some parts of York Government,
and a part of Connecticut.
A companion was provided for me; and we left home on the 24th of the third month, 1758.
We visited about eighty meetings, chiefly among those of other societies,
to our own satisfaction; and, apparently so, to that of the people generally;
who sat in their meetings admirably quiet; gave great attention to what was said;
and were much affected.
They were kind and affectionate; and seemed unwilling to part with us.
I was four months and five days from home; rode about one thousand miles,
and returned in peace,
and thankfulness of heart to the God and Father of all our mercies.

For some years after this journey, I seldom appeared in the ministry.
My friends, as well as myself,
were inclined to believe that if ever I had a gift for that service,
it was taken from me.
I was reduced very low; and great distress attended my mind.
I was often ready to say,
"`Is God`'s mercy quite gone? Will He be favourable no more?`" I went mourning on my way,
and had little comfort in my life.
In the night I wished for day; and in the day I wished for night.
None can conceive with what horror and anxiety I was attended,
unless they have been tried with similar desertion.
The cause of my being so tried, I did not then see;
but after I was in some measure mercifully restored, I believed it was to humble me;
that I might be brought to a more perfect and entire dependence upon the divine gift;
that so nothing of self should be present in my ministry.

After it pleased the Lord to revisit my soul with the light of life,
I felt a concern to arise, and increase, for the welfare of my fellow creatures.
I saw that the professors of Christianity were mostly at ease;
and that many under our name were contented with a mere profession of the Truth;
and I felt a desire that the careless and negligent might be
awakened to a perception of their dangerous situation.

In the year 1771, Samuel Neale, of Ireland,
being on a religious visit to Friends in America, came to my house,
on his way to Maryland.
Having no companion, I offered to bear him company.
He accepted my offer; and we set out in the fifth month,
and spent about a month in visiting the meetings of Friends, as far as West River,
those on the Eastern-Shore of Maryland, and those between Lewistown and Wilmington;
after which we rested a few days at my house.
Samuel intended to visit the meetings of Friends in New Jersey,
and no better companion offering, I accompanied him in that journey also.
From Wilmington we went to Salem; and after visiting all the meetings thereabouts,
we crossed the country to Cape May; and visited those of Great and Little Egg Harbour,
Shrewsbury, and other parts of New-Jersey.
Spending between six and seven weeks, to our mutual satisfaction.
We parted at a meeting called Solomon`'s; Samuel going to Philadelphia,
and I returning home, where I found my family in health.

Soon after my return, Samuel wrote to me,
desiring I would prepare for a journey to New England.
It was very pleasant to me, to find he had a concern to visit my native country;
for he had often said he saw no probability of making such a visit.
I felt willing to go with him, with the approbation of my friends at home,
of which I soon received their certificate; and made ready for the journey.
I left home on the 19th of the ninth month, 1771;
and went to our Yearly meeting at Philadelphia, which proved to me a good,
comfortable meeting, as I believe it did to many others.
Some friends, whom I highly esteemed,
informed me they were pleased with my intentions to accompany Samuel Neale;
which afforded me some encouragement, for I was in a low state of mind,
feeling great poverty of spirit.
I was apprehensive that Friends would prefer a better companion for him,
and might advise me to return home;
but Samuel seemed well pleased to find me prepared for the journey.

After the yearly meeting had concluded,
we set out for New-England on the 27th of the ninth month;
and proceeded directly to Rahway, where we had a meeting on First day; and,
in the afternoon, rode to New York.
Here we had a meeting on Second-day; and rested the day following.
On Fourth-day we attended the monthly meeting at Newtown, on Long Island;
after which we returned to New York.
From there we rode to Shappaqua, and so on to Ammawalk, Peachpond, Oblong,
Shearman`'s meeting, Oswego, Jonathan Hoag`'s, Over-the-Creek, Nine Partners,
and Salisbury, and had meetings at all those places to pretty good satisfaction.
From Salisbury we rode about one hundred miles eastward to Leicester;
had a meeting there, and lodged at the widow Earle`'s; another at Bolton,
and one at Salem.

Afterwards we proceeded in a north-easterly direction,
attending all the meetings of Friends, as far as Case`'s Bay;
and one on the other side of the Bay.
We crossed the Bay on the 27th of the tenth month, and returned the following day.
On our return, the wind was violent, and we appeared to be in imminent danger.
There were fourteen persons in the boat, which was a small one,
and the Bay eighteen miles wide, but, through divine mercy, we landed safely;
and went that night to Benjamin Winslow`'s. From there we travelled homeward,
fifty-five miles, to Berwick, and attended the quarterly meeting at Dover.
From there we went to Kittery, Barrington, Leaiping, and to a newly settled place,
fifty miles beyond Hampton, called Ware, and had meetings at all those places.
From Ware we returned to Hampton; and from there proceeded to Salem, Lynn, and Boston,
and so onward to Nantucket; visiting meetings on the way.
Afterwards we visited Rhode Island; and from there travelled through New England,
and York Government,
and arrived in Philadelphia after an absence of four months and a half; having travelled,
by land and water, about seventeen hundred miles, generally to good satisfaction.
I returned home in peace, and found my family well.

After this journey,
Samuel Neale and I were concerned to visit some parts of York Government;
and some within the bounds of Connecticut.
We set out on the 27th of the fourth month; and went to the quarterly meeting at Oblong.
We spent about six weeks in visiting the meetings of Friends,
and holding some among those of other societies.
On our return to Philadelphia, I parted with my beloved friend, Samuel Neale;
with whom I had travelled, altogether, about nine months.

On the 16th of the tenth month, 1772,
having obtained a certificate of the concurrence of my friends,
I set out in order to visit the southern provinces, in company with my friend,
Robert Valentine, whom I met at York-town, in Pennsylvania.
On the afternoon of the day of our meeting, we rode to Newberry;
where we attended a meeting the following day, which was not very satisfactory.
I was very much depressed under the weight of the undertaking,
which appeared a very great one, for two such poor striplings.
For though we were not young in years, yet we were so in experience as ministers.

Hitherto, I had generally travelled with old, experienced ministers,
upon whom I could lean, as I was too apt to do.
But now, under the prospect that the work would devolve with greater weight on me,
I was much cast down, although Robert was a valuable friend, and lively minister.
I mentioned to him my discouragement; but he spoke cheerfully,
saying he believed we should get well along, if our Master would go with us,
which he hoped would be the case.

On the following day we had a large meeting at Warrington,
and our Master was with us indeed, and favoured us with his life-giving presence.
It was an affecting time.
The power of Truth prevailed over all.
Life was in dominion.
Divine love filled many hearts; and we parted with the people in much love and tenderness.
This comfortable meeting relieved me of my fears, and renewed my faith.
We now went on pretty cheerfully; under the hope that we should be favoured,
from time to time, with fresh supplies of Divine help, through our journey.
We visited meetings on our way to Fairfax; and were at their monthly meeting,
and several others in that neighbourhood.
At that time our valuable friend, John Churchman, was at Fairfax;
and we attended several meetings with him.
Robert and I had an evening meeting at Louisburg.
It was held in their courthouse, and many of their great people were present.
It proved a very trying time to us both; such as I had never known before.
But, after we had been sufficiently proved and mortified, we were favoured with a good,
comfortable opportunity to relieve ourselves; for which I was truly and humbly thankful.
John Churchman remained at Amos Janney`'s, in Fairfax,
until we had visited all the meetings in that neighbourhood.

After finishing this service, we returned to Amos Janney`'s;
and from there set out on our journey southward.
At parting with John Churchman, he told us he had no objections to our going forward,
which afforded us great encouragement.
I was inclined to believe he would advise me to return home,
and not attempt further to prosecute my enterprise.
I concluded he would perceive our weakness, and be honest to us in the cause of Truth;
and I felt willing to receive such advice,
not desiring to proceed without Divine approbation.
But, notwithstanding we had been encouraged to proceed, I went on in great fear;
having a daily sense of my own insufficiency for so great and important a service.
We, however, ventured to proceed to Hopewell,
and attended all the meetings in that neighbourhood; then went to Smith`'s Creek,
from there to Douglas, Camp Creek, Fork Creek, and Genito; to John Johnson`'s,
in Amelia county; to South River, a branch of James`'s River, to Stanton,
and so on to North Carolina.
We had meetings at all those, and some other places.
In New-Garden settlement we were at one quarterly meeting, three monthly meetings,
and eighteen public meetings.
Though we had our trials and baptizing seasons, and felt need of daily assistance,
the great Shepherd of Israel was near us, and favoured us with help.
We felt great love for the people; and I hope our visit may be useful to some of them.

Soon after we entered New-Garden settlement, and before we had had a meeting there,
my companion heard a report that a letter had come for me,
and that it contained bad news.
It was said the letter had passed us, and when or where it would be found,
was very uncertain.
My companion consulted with some friends on the subject;
and they thought it would be best to conceal the report from me,
as we were just going to the first meeting in the settlement.
However, as we rode along, he thought it right to inform me of the rumour;
and told me it was reported I was sent for home.
On hearing it I was filled with concern, the enemy was busy, and I was weak,
yet I continued my journey, although I had poor meetings.
I supposed my friends were uneasy with my proceedings;
and had sent to request me to return.
The report concerning the letter spread among the people;
and it was currently asserted that Wilmington was burnt to ashes,
that all my property was consumed, and that I was sent for on that account.
These were heavy tidings; and all true, for any thing I knew to the contrary.

After several days of great anxiety,
a hope arose in my mind that it was not so bad as was reported; for,
as I turned my mind towards home, it seemed to me,
that my dwelling house at least was safe.
I had now been about ten days under this trouble,
when we lodged at the house of a Friend whose wife was a sensible, religious woman;
well acquainted with the snares of the enemy; and she,
hearing me say something of returning, as I could hear nothing further of the letter,
told me she believed there was little or no truth in the reports,
but that it was the work of Satan and his emissaries,
to hinder my service and send me home.
This was a seasonable caution.
When we had visited nearly all the meetings in that neigbourhood,
and as we designed to proceed to Bush River, in South Carolina,
I thought it best to use every means to find the letter, before we went further.
I therefore hired a young man to go back in pursuit of the letter as far as Hillsborough,
sixty miles, if necessary.
After proceeding about thirty miles in the search, he found it; and brought it to me,
just as we were going into a meeting.
I opened and read the letter, much to my comfort.
There was no account of a fire, or any other unpleasant occurrence in it.
Thus all my uneasiness was removed.

This storm being happily blown over, we set out for South Carolina.
Zachariah Dicks, John Carter, William Lindley, and John Unthank,
accompanied us to Bush River, two hundred miles; which we travelled in five days.
Two of the Friends remained at Bush River, while we went to Georgia.
We went afterwards to Wateree and Pedee.
At the latter place we had two meetings with Friends.
There we parted with the four Friends before mentioned.
They had been our affectionate and pleasant companions for about a month.
After our separation, Robert and I felt lonesome;
having to ride one hundred and twenty miles before we could come among Friends again.
During two days we had guides to conduct us; then,
hoping we should be able to find the way without their assistance,
we advised them to return home.
We arrived at Richard Cox`'s, at Neuse River, in safety;
and after having two satisfactory meetings there,
we rode fifteen miles to Great Contentney; where we had a meeting.
From there we went to Henry Horne`'s, at Tar River, and had a meeting at his house;
which was a poor, low time.
The professors there seemed inclined to the Baptists.

From Tar River we went to Rich-Square; and, after attending their meeting,
we set out towards the old settlement, in North Carolina.
As we proceeded towards the lower settlements, in Carolina and Virginia,
among a wise people, as I supposed, fat and full, possessing great numbers of slaves,
I was very pensive, and so much depressed, that I would gladly have passed them by,
and returned immediately home.
But I saw no way for me, but to look to my Divine Instructor;
and depend on Him who had hitherto been our sufficient helper,
in every strait and difficulty.
After a time of trial, I was favoured with a degree of fortitude and resignation.
I went down among them in fear, but we found some tender, loving, well inclined people;
and were favoured with heavenly help, and enabled to proceed, I hope,
to the honour of Truth, and advantage of the people;
for many of whom we felt a tender regard, and parted with them in much love.

Although they were generally in the practice of keeping slaves,
yet they had begun to see the error of it,
and were desirous to be relieved of the burden; but saw no way to effect it,
to the satisfaction of themselves and their slaves,
because of the cruel laws in force in these colonies, by which,
if a man set his slaves free, they would be liable to be seized,
and sold to the highest bidder; which appeared grievous,
both to themselves and their owners.

We visited nearly all the meetings in the lower parts of North Carolina and Virginia,
to our satisfaction.
We then passed into Maryland; visited the meetings on the Western Shore,
as far as Baltimore; from which we came directly home.
I found my family and temporal concerns as well as usual;
and had great peace and satisfaction of mind,
under a thankful sense of the many favours we had received,
and that Divine assistance had been afforded in every trying season.
We had been engaged in this visit just five months,
had travelled nearly three thousand miles,
had attended one hundred and five Public meetings,
and arrived at home on the 16th of third month, 1773.

After my return from this journey, I did not travel far from home, until the fifth month,
1776; when, in company with John Perry,
I left home to pay a religious visit to Friends in New-England.
At Rahway we met Rebecca Wright and Phebe Yarnall,
who were engaged to pay a similar visit, and we travelled together about seven weeks.
We were at many meetings in York Government, Naraganset, and Rhode Island;
and attended the meetings on the way to Nantucket.
From there, we returned to the quarterly meeting of Sandwich.
After the close of that meeting, we parted from the two women Friends, before mentioned.
They went towards Boston, and from there eastward; we returned towards Providence,
and visited all the meetings in those parts.
From there, we crossed Connecticut, through Hartford to New-Milford, and to Oblong.
From the Great Meadows we passed to Kingwood, New-Jersey, into Bucks county,
Pennsylvania, and from there home; from which I had been absent about ten weeks.
We had travelled, by land and water, eight hundred miles.
I was favoured with peace of mind, and found my family well.

1779+++.+++ I am now drawing towards the conclusion of life; being, this day,
seventy two years of age.
For the encouragement of others,
I will now briefly recapitulate some of the kind dealings of Providence towards me.
The God of my life, my Maker and Preserver, has been propitious to me,
from youth to old age.
The fear of the Lord, which preserves from evil,
was placed in my heart when I was but eight years old;
so that I was afraid to offend Him.
In the twelfth year of my age, I was mercifully visited,
and called out of the vanities of the world; at which time I received a promise,
that if I sought first the kingdom of God, all other necessary things should be added;
and I have found the promise true,
for I never have lacked any of the good things of this life.
I have been blessed with sufficient for myself and friends,
and something to spare to the poor; and I esteem it a great favour,
that I received a disposition to communicate to those who stood in need.

If all men would "`seek first the kingdom of heaven,
and the righteousness thereof,`" and carefully attend to the leadings of the Holy Spirit,
with which all might be favoured,
I believe they would be blessed with a sufficient portion of wealth.
O that mankind were wise! and would early seek that treasure which comes from above;
and which neither moth nor rust can corrupt, nor thieves break through and steal!
And may we all beware of loving the world; and living at ease,
in the enjoyment of its good and pleasant things!
Even those who have been favoured with remarkable Divine visitations,
and have been put in possession of "`the upper and the
nether springs,`" have great need to be on their guard.
When we enjoy health and plenty, and all things seem pleasant around us,
we are prone to forget the Lord, and neglect those "`things that belong to our peace.`"
This I know, by sorrowful experience.
In this way I was brought into a long, dark, and mournful situation;
and kept from yielding obedience to my known duty respecting the ministry.

Although I had been called out of the world, and uncommonly favoured, as before related;
although I had forsaken the vanities and flesh-pleasing
gratifications in which I had delighted;
although I had left the college in a way so mortifying, had given up all to death,
and freely borne the cross of being esteemed a fool by the world;
afterwards joining with the despised Quakers, adopting their language,
dress and behaviour; (all which I could not have done without Divine assistance;) yet,
after all this, I was so forgetful, and ungrateful to my heavenly Benefactor,
that it is a wonder I was ever restored.
And I have no doubt that thousands, through negligence,
even after they have been called out of the world, and have run well for a season,
have been finally lost;
swimming away in the riches and pleasures of this transitory state.
This I have written for a warning to others.

In the early part of the winter, after my return from New-England, in 1776,
I was reduced to a poor state of health, and so continue.
I believe I have not lately been ever clear of a slow fever;
but have generally been able to go to our religious meetings, at and near home;
sometimes to Philadelphia, and once into Maryland, the lower counties on Delaware, etc.

[.signed-section-signature]
David Ferris

[.signed-section-context-close]
Wilmington, 5th Mo. 1779.

[.postscript]
====

P+++.+++ S. I do not think it probable that Friends will
think the rough remarks and observations I have made,
worth publishing; but they may possibly be of some use to my family, to whom, therefore,
I leave them.

====

[.signed-section-signature]
David Ferris
