[short="Testimony From Wilmington Monthly Meeting"]
== A Testimony

[.blurb]
=== From Wilmington Monthly Meeting, In the County Of Newcastle, on Delaware, Concerning David Ferris.

He was the son of Zachariah and Sarah Ferris, and was born in Stratford,
in Connecticut government, New-England, the 10th of the third month, 1707.
His parents being Presbyterians, brought him up in that way;
his mother being religiously disposed, and much concerned for her offspring,
frequently gave them good advice and admonition,
which had some good effect with this our friend, as he has often been heard to express.

We find, by some remarks he left, that about the twelfth year of his age,
he was frequently visited and called unto by the Divine Monitor in his heart,
to forsake evil and youthful vanities, which he delighted in; and,
by being in a good degree faithful thereto, was, for a time, preserved from them;
but for lack of attending to that which would have continued to preserve him,
the pleasures and vanities of this world got hold of his mind,
so that he took much delight in airy and vain company, music and dancing,
and such like amusements, until about the twentieth year of his age;
when it pleased the Lord to visit him with a sore fit of sickness,
which proved of lasting advantage to him,
as it occasioned him to take up a fresh resolution; to forsake the evil of his ways,
and turn to the Lord with full purpose of heart; which he was, through mercy,
favoured with ability in measure to perform.

He still continued in profession with the Presbyterians,
not having any knowledge of Friends; although,
by attending to the teachings of divine grace,
he became convinced of the principle we profess;
and hearing of a yearly meeting of Friends to be held on Long Island, went to it,
with desires to discover whether they were a living people or not,
for such he desired to find; where he met with what he often longed for,
a people that worshipped God in spirit and in truth;
which was a great strength and confirmation to him, in forsaking the errors of his youth.
And by yielding obedience to these inward motions, he gained strength,
and was more and more enabled to bear a faithful testimony to the truth,
as it was made known to him.
In the sixth month, 1733, he removed to Philadelphia,
where he joined in religious fellowship with Friends.
In 1735, he married Mary, the daughter of Samuel and Sarah Massey;
and in 1737 removed to Wilmington, in Newcastle county,
where he resided the remainder of his days.

He made some appearance in the ministry about the year 1734, but,
through unfaithfulness to the divine call, he from time to time put it off,
and remained in a neglect of duty therein, upwards of twenty years;
although he was often warned, both immediately and instrumentally,
in a remarkable manner; which, at length, produced a submission to the Divine will;
so that, in the year 1755, he was made willing to give up thereto,
and therein found great peace.

He travelled through several parts of this continent in the work of the ministry; and,
by certificates produced on his return home, it appeared, that his conduct, conversation,
and labours abroad, were exemplary and edifying,
tending to the advancement of truth and righteousness.
His doctrine was sound and acceptable to the honest-hearted,
though sharp against the hypocrite and rebellious;
yet tender to the mourners and disconsolate.

He was very serviceable in our meetings for discipline, which, with other meetings,
he diligently attended;
not suffering his outward affairs to hinder him
from what he believed to be his religious duty.
And although he followed shop-keeping for a living,
it was his practice to shut up his shop,
and take his family with him to week-day meetings, often expressing,
for the encouragement of others, that he believed it was attended with a blessing.
He was free and open-hearted to entertain Friends;
and concerned to bring up his children in plainness,
and instruct them in the fear of the Lord,
believing that to be the best portion they could inherit;
remarkably charitable to the poor, and often administered to their necessities.

Bodily weakness attended him during the last three years of his life;
and near the close of his days, he was much afflicted with sickness,
which he bore with patience; often expressing his prospect of his approaching end,
and his resignation therein; saying, "`All is well.`"
Several Friends being present, after a time of silence,
he in a lively manner repeated the expressions of the apostle, "`To me,
to live is Christ, and to die is gain.`"
He departed this life, the 5th of the twelfth month, 1779, aged upwards of seventy-two,
a minister about twenty-four years.
On the 7th of the same month, his corpse was interred in our burying ground in Wilmington.

THE END.
