== Chapter I.

[.chapter-synopsis]
* From his birth in 1707, to his admission into College

When I consider the situation of man in his fallen state,
and the great change that all experience who
have been delivered from the power of darkness,
and translated into the kingdom of the dear Son of God; that,
in order to attain to this happy state,
all must experience a mortification of their natural tempers and evil propensities;
must know the "`old man`" to be slain, and the "`new man`" to be put on, which,
after God, is created in righteousness and true holiness; and that,
in order to walk in the new and living way, we must know old things to pass away,
and all things to become new; I say, when I consider these things,
I feel a concern for my fellow men, that they may become acquainted with this change.
And apprehending that I have had some acquaintance with it,
by passing through various dispensations of trial and affliction,
I am inclined to leave some account of them to posterity; to show to those who follow,
that the Lord is ever near, and will be found of those who seek him early;
that He is long-suffering towards those who go astray,
and merciful to all who sincerely turn to Him:
hoping it may minister information and encouragement to
weary travellers in the same road;
and induce them cheerfully to comply with divine requirings.

I wrote a short account of the fore part of my life in Latin,
continued to about the twenty-fifth year of my age.
The many difficulties and dangers in my way,
and doubting whether I should hold out to the end,
induced me to keep my history in a language unknown to those about me.
I concluded that if I should hold on my way, I might afterward translate it into English;
and add to it, as I found freedom.
And now, after about twenty years experience of divine support and preservation,
having great cause to say that "`God is good to them who seek Him`"--
that none seek Him in vain--and that his tender mercies fail not;
I am inclined to translate it, hoping it may be useful, at least,
to some of my posterity.

I was born at Stratford, in Connecticut, New-England, the 10th day of the third month,
1707.
My parents, Zachariah and Sarah Ferris,
made profession with the people called Presbyterians; and in that way I had my education.
My father, while I was very young, moved to a place called New Milford.
It being a newly settled place, I had not the advantage of a school; but,
under the care of my mother, I soon learned to read in the Bible,
and understood that there was a Supreme Being, who made all things,
and preserved and upheld them in their order; and that, as the workmanship of his hand,
I stood accountable to Him for every part of my conduct.
About the eighth year of my age, I was informed that the Divine Being was self-existent,
without beginning and without end; and not being able to understand how that could be,
I sometimes thought so intensely on the subject that I became much bewildered.
At length it was shown me, that the proposition was too high for my comprehension,
and I received something like a reproof for searching into things beyond my capacity.
From that time I was fearful of prying into such deep mysteries.

My mother, being a religious woman, and much concerned for the good of her offspring,
both temporally and spiritually, was frequent in giving them good advice and admonition;
desiring that we might shun the paths of error; and teaching us, by her own example,
as well as by precept, to walk in the ways of virtue, which lead to peace.
This was a great help to us while young,
and was not easily forgotten when we came to maturity.
Death was a frequent subject of my thoughts; and, in the twelfth year of my age,
I was frequently called by the Holy Spirit to forsake evil, and leave youthful vanities,
which I then delighted in, and to be sober and circumspect in all my ways.
By attention to the divine call, and to the reproofs of instruction daily communicated,
I was preserved from evil; and saw something of the beauty of holiness,
the happy state of the righteous in the world to come,
and the moving situation of the wicked, when they put off mortality,
and hear the awful sentence pronounced, "`Depart, ye cursed!`"

About this time, a little circumstance occurred that much affected my mind,
and afforded me lasting instruction.
As I was riding through a river, against a rapid cur rent,
a young dog attempting to swim after me, the stream being too strong for him,
could not keep up with my horse.
He appeared to be in the utmost distress, even to desperation.
As my mind was filled with pity for the poor animal,
it was opened to view--the awful amazement a poor soul must be in when leaving the world,
destitute of hope.
As simple a circumstance as this may appear, it was, I believe, of use to me for years.
I was very careful of my thoughts, words, and actions, for several years afterwards:
the fear of the Lord preserving me from evil.
My mind was humbled under a sense of my daily want of divine help;
and as I abode under a religious concern, attending to the reproofs of instruction,
which are the way to life, an increase of light and life was communicated to me,
so that I came to delight in virtue.
As my desires and care for divine things increased, the knowledge of them was unfolded.
I could truly say, the Lord was my delight.
And for some years, as I dwelt in his fear, his yoke was easy, his burden light,
and all childish vanities were burdensome.

While I kept near the spring of life, with my mind fixed on the true object,
the world and the things thereof lost all their lustre.
But, alas! not keeping my eye single to the light, I lost my Leader; and then,
by little and little, the world rose again with splendour to my view.
Earthly delights and vanity got such hold of my affections,
that I took great pleasure in airy and vain company.
This was an unspeakable loss to me,
and I mention it that others may take warning by my harms.
It seemed almost miraculous that I was ever restored from this lapsed state.
My mother mourned over me, and often advised and urged my return,
showing me the danger of such a course of vanity.
Yet I was not wholly forsaken by my inward Monitor and former Guide.
At times it reproved me, at other times called me, wooing and pleading with me to return.
Sometimes, in the midst of my vanity, I saw that I was in the way to death;
and that it would land me in everlasting confusion if I did not forsake it.

Sometimes my concern was so great, that I was obliged to leave my vain companions,
and retire so full of trouble and distress,
that I had no satisfaction until a considerable time afterward.
During these seasons of affliction,
I was ready to promise to forsake my vain course of life,
and to covenant with the Lord that I would do so no more,
provided he would be pleased to grant me his assistance.
But my efforts, being too much in my own strength, proved unavailing.
Vanity so prevailed that I took great delight in music, dancing,
and other vain amusements.

In the twentieth year of my age, I was visited with severe illness; so that I,
and those about me, had very little hope of my recovery.
Then death stared me in the face; and a dreadful scene of woe, anguish,
and misery opened to my view.
It appeared clear to me that if I were then taken off the stage of action,
I should be unavoidably lost; and that evil spirits were waiting round me,
to convey my soul to the mansions of misery and everlasting darkness; so that my horror,
anxiety, and distress were inexpressible.
In the utmost anguish of mind, I cried to the Lord for help; promising amendment,
if more time and ability were afforded me;
and it pleased a kind Providence to be propitious to me;
so that I was restored to health; and, in about a month, was able to walk about.

After my recovery I remembered the distress I had been in, and the promise I had made,
when under the dreadful apprehension of everlasting misery and destruction.
I saw the necessity of a faithful performance of my vows.
I was sensible that there was a work to be done;
and that if I did not now comply with my promise, I should have to pass through the same,
or rather a worse scene of misery and distress.
It appeared probable that a more convenient opportunity
for repentance than the present would not be afforded;
and I concluded that this was the time to turn from vanity; forsake my evil ways;
and renounce all my sensual delights.
But, when I had resolved to begin the necessary work of reformation,
the adversary of all good tempted me to believe that it
was too late to think of obtaining peace with my Maker;
for this plain reason, "`that, as there was a day or time, in which men might be saved;
so, if they let that opportunity pass away unimproved,
it would be in vain to attempt it afterward.`"
He suggested, that I had had such a day of visitation, and had passed it by;
that I had been uncommonly favoured with help, and for a time did not accept of it;
that I had been made a partaker of the Holy Ghost;
that I had tasted of the good word of God, and the powers of the world to come,
and had fallen from it;
so now it was impossible that I should again be renewed unto repentance;
seeing I had crucified the Son of God afresh, and put Him to open shame.
This reasoning appeared so strong, and so consonant to the apostle`'s doctrine,
that I gave up the point; and concluded it was too late to attempt a return,
with hope of acceptance.

From that time, during the space of about two months, I never sought for mercy;
but remained in utter despair.
My distress was as great as could well be supported without loss of reason.
I daily wished for death, so that it might occur without laying violent hands on myself;
which I was not much tempted to do.

It was usual with the young people of our neighbourhood
to spend much of their time in vanity and merriment,
forgetful of God their Creator,
as if they had been made to please themselves in the gratification of a sensual mind;
and, provided they were not profanely wicked,
the elderly part of society were not very uneasy with it.
But, in the year 1727, there was a great reformation at New-Milford,
among the young people of the Presbyterian profession.
They had been awakened by the immediate operation of the Holy Spirit on their own minds;
and were brought into great concern for their future well-being;
under which they had no outward assistance.
The apostolic doctrine of "`Christ within,`" and of being "`led by
the Spirit of God,`" was denied by the priest and many of the people,
who appeared to have little sense of a Divine Teacher in themselves;
but asserted that revelation had now ceased,
and no such thing was to be experienced in this day.
As I had been the companion of those young people in vanity and dissipation,
they (knowing nothing of my inward condition,
which I had not discovered to any) generally applied to me for counsel and advice;
and I was much concerned on their account; being desirous of affording them assistance,
although I had no hope of relief at that time for myself.

My trouble continued and increased; so that I had no satisfaction in life.
On a certain day, in this season of despair and deep distress,
I concluded to leave my native land and go into some foreign country,
to spend the residue of my days; where I purposed to remain unknown,
and that none of my relations or acquaintance should know what was become of me.
Being, in my own apprehension, a poor, lost, reprobate creature,
I was not willing to remain at home, to be a disgrace to my relations and country people.
This was a day of the deepest affliction and distress that I had known.
Towards evening, as I followed the plough, my attention was arrested, as it were,
by a still, small voice, saying:
"`The blood of Jesus Christ his Son cleanseth from all sin.`"
But I put it by; saying in my heart: "`It is too late;
there has been a day wherein I might have been cleansed; but, alas!
I have let it pass over my head forever.`"

Some time after this, (perhaps half an hour,
while I was musing on what land I should flee to,
the same words passed through my mind again, with more authority than before,
and commanded my attention rather more closely than they had done;
but I again put them by; concluding I had lost all right to apply them to myself.
So I resumed the consideration of my flight to a foreign land.
In the mean time my sorrow and anxiety of mind increased,
so that I was not well able to support it, or go on with my business.
But while I was still musing, the same words, unsought for and unexpectedly,
passed through my mind with greater power and authority than at any time before:
"`The blood of Jesus Christ his Son cleanseth us from all sin.`"
At the sound of them my soul leaped for joy.
I felt that a door of hope was opened, and said in my heart, "`If all sin,
why not mine?`" Then a living hope sprang in my soul.
I saw the arms of mercy open to receive me,
and the way cleared before me as a road through a thicket.

I was now filled with joy unspeakable;
thanksgiving and living praise to my redeemer arose in my heart for
the experience of so great and marvellous a deliverance.
That my feet should be plucked out of the mire, and set upon a rock; that I,
who had no hope just before,
should now be favoured with a well-grounded assurance of pardon and acceptance,
was a mercy never to be forgotten.

From this time I sought for divine assistance; and, in infinite kindness,
a hand of help was extended for my restoration, and the healing of my backslidings.
Then I was enabled to sing upon the banks of deliverance,
and praise the name of Him who lives for ever.
The Holy Spirit, that blessed Teacher, whom I had formerly been favoured with,
but had forsaken, was now restored, as a Leader and Teacher,
to direct and instruct me in the way to peace and rest.

From this time my mind, after such great favour,
was humbled and made subject to the cross of Christ,
and heartily willing to take it up daily, and follow Him, my kind leader,
in the narrow way of self-denial.
And as I was obedient, He led me to forsake my vain course of life,
and all those youthful delights and sensual pleasures
which were displeasing to my dear Lord and Master;
who in wonderful mercy had lifted me out of the dungeon,
and heard my prayers in a time of deep affliction.
He now became my Director in all things; showing me clearly what my duties were,
and enabling me to perform them in an acceptable manner.
But if, at any time, I acted in my own will, I lost my strength,
and found no acceptance or benefit by my performances; by which I gradually learnt,
that I could do nothing, acceptably,
without the immediate assistance of the Spirit of Christ the Redeemer.
Thus I found a necessity to apply continually to my only and all-sufficient Helper,
and humbly to wait for his assistance and direction: and as I was faithful,
He led me into the path of life, which, if continued in,
will terminate in everlasting peace.

Having gradually learned that nothing of a religious nature could be effectually done,
without the immediate assistance of the Holy Spirit,
I may humbly acknowledge that I was wonderfully favoured with Divine instruction;
far beyond my expectation, and infinitely above my deserts.
I was led, as it were, by the hand, and helped over every difficulty that attended me.
But the adversary of my soul tried every stratagem to
draw me aside from the path of virtue.
He strove, night and day, to deter me from walking in the narrow way;
representing the difficulties to be so great that I could never hold out to the end;
and that all my attempts would be in vain.
He seemed to be continually present, whether I was awake or asleep,
disquieting my mind as much as possible.
But my prayer was incessant for divine aid;
that a stronger than he might appear for my help, and dispossess him.
And, in about a year after I had been raised from the pit of despair, as before related,
I received a promise that "`the God of peace would bruise Satan under my feet shortly.`"
Faith was given me to believe in this promise, and I hoped for a speedy deliverance.
But he continued to afflict me with his assaults, with temptations, and evil suggestions,
for some months afterward.
Not withstanding which, I still believed the time would come, according to the promise,
and I prayed for its fulfilment in the Lord`'s time.
At length, a stronger than he did indeed come, and cast him out,
and wholly dispossessed him; and not only bruised him under foot,
but removed him far from me.

The power of the enemy to assault, or in any wise to disquiet me, was now taken away;
neither was he able to lay any temptation before me.
Now was my soul daily filled with thanksgiving and living praise for this deliverance;
as well as for all other the manifold mercies and favours of God,
from day to day bestowed upon me, "`a worm and no man.`"
To the honour of his great name, who hath done marvellous things for me,
and to the praise of his grace, I may say,
that the adversary of all good was not only thus prevented from troubling me;
but the fountain of divine life was opened,
and the water thereof flowed so freely and plentifully into my soul,
that I was absorbed in it, and so enamoured thereby, that all the riches, honours,
and vain pleasures of this world, had no place in my affections.
In this state I longed to be with Christ; which, I was sensible,
was better than to be here.
I do not know that there was one moment, whilst I was awake,
for the space of nearly two years,
in which I could not sing living praises to Him who liveth for ever and ever.
No losses, crosses, or disappointments did, in any degree, disturb me;
at least not perceptibly, either to myself or others;
for my delight was in objects very different from
anything which this world can give or take away.
I dwelt as in the mount, out of my enemy`'s reach; and, apparently,
out of danger from any evil.
Here I hoped to remain all the days of my life, and that I never should be moved.

However strange this relation may appear to many, I believe it is strictly true.
I am sensible that some, who have no experience in things of this nature,
may smile at this narrative;
but others may be glad to see in it a relation of circumstances, corresponding, perhaps,
to their own experience of trials passed through,
or favours received from the divine and all bountiful hand.
I have no vanity in penning this account; but rather a fear,
lest the succeeding part of my life should not correspond with
the favours conferred upon me by a gracious benefactor;
as stated in the preceding narrative.

While I dwelt as on the mount, as before related, my spiritual eyes were opened;
my understanding enlightened and enlarged.
I then wondered to see that the world, as far as my knowledge of it extended,
was more in show than in substance; better in appearance than in reality;
that even the true form of godliness was too little to be seen.
I had conceived that the people among whom I was educated were
better than the other professors of Christianity;
but when my eyes were thus anointed to see clearly,
I found very little true religion among them.
Primitive purity appeared to be very much lost.
I was affected with sorrow and mourning,
on account of the great declension among the
professors of the Christian religion in general:
for the more I was concerned to examine the subject, and sought for divine wisdom,
the stronger were my convictions, the clearer my views, of a general apostasy;
that a life of self denial, a dwelling under the cross of Christ,
was very little regarded.

Before this period I had had a desire to acquire a knowledge of the languages,
and other learning,
and now my mind became satisfied that it would be right for me to pursue these objects;
but, before I give an account of my progress in this pursuit,
I will recur to a subject mentioned before.
It was said, that in the year 1727,
some of my companions were brought under a concern for their future happiness.
This concern spread, and so increased among the young people at New-Milford,
that it became general.
Many that had spent much of their time in vanity and mirth, were, at this period,
exercised for their eternal welfare; crying out, as some did formerly,
"`What shall we do to be saved?`"
I think there were nearly sixty of us in about one year,
who joined in close communion with the Presbyterians,
in the participation of the bread and wine.
As we were faithful in the discharge of our duty, as far as it was manifested to us,
and endeavoured to advance in the path of virtue, our understandings became illuminated,
so as to perceive some things in a different light from
that in which they were seen by our fellow professors;
both with respect to practical and doctrinal points.
Sometimes we ventured to mention some of our sentiments,
on subjects in which we apprehended there was a difference between us,
which soon involved us in trouble.

We were accused of holding heretical opinions;
and brought before the church to answer the accusation.
Neighbouring ministers were called in to deal with us on this occasion,
but they made little of it.
I had previously stated, in writing, the points of difference between us;
with the reasons for our dissent; and when the congregation met to deal with us,
I presented it to them.
Whereupon a committee was appointed to examine the document,
and to judge whether it would be proper to read it in that assembly.
On their return, they reported favourably; and it was read.
When any difficulty occurred, I was desired to explain my meaning,
which I did accordingly.
After it was read through, they sat silent for some time.
At length, an ancient man rose, and said:
"`If this be all wherein our younger brethren are supposed to differ from us,
there is nothing in this writing that I cannot unite with, and say '`Amen`' to.`"
Others, of the foremost rank, expressed the same opinion,
upon which it was concluded that our sentiments were
not so heterodox as to prevent communion with us.
It was settled accordingly, and we were pronounced members in full communion.

But, notwithstanding this conclusion, a report was circulated,
and generally believed among the people, that we were heretics;
and I was considered as a leader among them.
Some called us Quakers; but we knew nothing of that people,
and thought it as ill a name as they did;
though we considered it our duty patiently to bear the
reproach cast on us for the Truth`'s sake.

But to continue the account of my proceedings relative to the acquisition of learning.
I first went to the teacher in our parish, and stayed with him, as a scholar,
but one month, until he refused to teach me any further; alleging,
as a reason for his refusal,
that my opinions were too heretical to admit of my reception into the college;
so that my labour would be useless; or, at least, not answer the end proposed.
He was a weak man, and had but little experience in religious concerns,
in which I had now acquired some knowledge; besides,
he was not scholar enough to teach me to any purpose, which made we willing to leave him.

After this I soon concluded to go to Danby, about thirty miles from my father`'s house,
and to place myself under the tuition of a teacher whose name was Moss.
I had heard that he was a good scholar, and a good Christian.
These qualities, I thought, would make the situation pleasant to me,
and I was not disappointed.
Whilst I was preparing to go to him, I was suddenly taken sick; and became so ill, that,
in a few hours, it appeared doubtful whether I should recover.
I was in hope that my departure was at hand,
though I did not then see how I should be disposed of.

Whilst I was lying very ill, though my understanding was calm and clear,
and my will fully resigned, my mother came to me,
and asked me if I thought I should die of that illness.
I answered, I did not know how that might be, but should be glad to leave this world,
if it were the will of God.
After some further discourse, my mother left me alone; and soon after,
my soul (as I apprehended) departed from the body.
On which I was filled with joy, concluding I had done with this world,
and all its troubles.
Being now freed from the shackles of mortality,
I went on rejoicing toward the land of bliss, with great alacrity of soul,
and as I departed, I thought I saw my body lying a lifeless lump of matter.
But as I went forward,
I was met by some excellent person whom I took to be the Son of God,
and who informed me that I must not go; saying: "`Thou must return to the body;
thou shalt not die, but live, and declare the wonderful works of the Lord.`"
I was troubled to think of returning, to be confined to a body of clay.
However, I stood still, musing and waiting for direction;
when it appeared to be my duty to submit.
I then said, "`The will of the Lord be done,`" and immediately I was in the body.

Soon after this, my mother came again into the room,
and repeated the question she had put to me before, to wit,
whether I thought I should die at that time.
I answered, "`I shall not die with this illness.`"
She seemed surprised that I should answer so positively, and without hesitation;
and then, queried how I knew that.
"`For,`" said she, "`you told me, about an hour ago,
that you did not know whether life or death would be your lot at this time.`"
I then gave her an account of the circumstances just related,
which satisfied her respecting my confident answer.
She was filled with joy, and thankful acknowledgment to the Fountain of all Good,
that I was restored to her,
and that He had been so propitious to me as to reveal
his will in so clear and indubitable a manner.
At this time my mother and I were both Presbyterians,
and continued in that profession several years after this event.

Being now sensible that my continuance here was required for a longer season,
I became very thoughtful,
lest I had been mistaken in supposing I had obtained
the knowledge of my Divine Master`'s will,
respecting my learning the languages, etc. and was brought into a strict examination,
whether I was in the way of my duty in making the attempt;
for I had now a clearer sight that human learning was
insufficient to prepare for the ministry of the Gospel,
than I had before.
Being humbled, and self entirely reduced, I was willing,
if I could discover that my attempt was wrong,
to acknowledge my fault to Him who knoweth all things, repent of my rashness,
and confess my error;
especially to those to whom I had made known my intentions on the subject.
I had told some of my companions that I saw it my duty to acquire learning;
and some considerable time before there was any probability of it,
I had gone so far as to say that I should obtain it.
If, therefore, I had been mistaken, there was now great need of my knowing it,
and making proper acknowledgments on every hand; and to be more careful in future,
not too easily to take any thing for granted, and then report it as a certainty.

During this sickness, which continued about three weeks,
I earnestly desired that I might receive wisdom,
to direct me in a way acceptable to the Lord;
and although I had a strong desire for the acquisition of knowledge,
yet I was willing to submit to the disposing hand of Providence;
and durst not ask for anything but with entire submission to the Divine will;
being sensible that if I obtained it in any other disposition,
a blessing would not attend it.
At length, being on the recovery, and very much exercised in mind on the subject, I had,
one morning, as I lay in bed, such a clear manifestation of the Divine will thereon,
as left no doubts on my mind respecting the course I ought to pursue,
and so I proceeded to prepare for admission into college.

After this I soon recovered, and went to the teacher at Danby,
of whom I had heard so good a character, as before mentioned.
I was well satisfied with him, as I believe he was with me.
He was a religious, tender spirited man; and, I believe,
"`a lover of good men,`" in the apostle`'s sense.
After I had been with him some time, one of his congregation said to him,
"`I understand you have a heretic with you, preparing for admission into college.`"
He replied, "`I wish all my congregation were such heretics as he is.`"
To which his neighbour made no reply.
This he told me himself soon after it occurred.
I stayed with him six months, when his other scholars left him; and,
as it did not suit him to attend on me alone, I went to one Robert Trett, at New-Milford,
and spent about six months with him,
when he thought me sufficiently learned for admission into college.
Accordingly I went there, passed an examination in relation to my learning,
and was admitted without any mention of heresy.

After my admission I endeavoured to keep humble, and to live in the Lord`'s fear,
so as to be a pattern of lowliness of mind.
I was desirous to be serviceable to mankind,
and endeavoured to keep to that which alone could qualify for it.

Here I think proper to remark, that in one respect I was apt to err,
until experience taught me better.
This was, talking too much about religion in my own will and time.
At length I found it tended to poverty, and I learned, when in company,
not to be forward to enter into any discourse concerning religion, or any other subject,
but to be content to keep silence and be esteemed a fool, until Truth arose,
a subject clearly presented, and liberty was given for conversation.
Then I found a qualification to speak to the edification of others,
and my own peace and satisfaction.
I mention this for the benefit of others,
being convinced that many who have had experience of the Truth, and have, in some degree,
witnessed a change of heart, have talked so much on religious subjects,
that their souls have become barren, so as scarcely to know when good cometh.

Now, as I dwelt under an humble sense of my own nothingness,
and sought for the direction of Truth, I found the Lord to be near by his Spirit,
to instruct me in all things necessary to be known;
which were clearly manifested from time to time, as I was able to bear them.
