== Chapter II.

[.chapter-synopsis]
* From his entrance into College, to his finally leaving it, and declining to take a degree

At my entrance into college my principles generally
corresponded with those held by the Presbyterians.
But I now began to think it was time to examine for myself,
and no longer trust in the judgment of my forefathers.
I found it necessary to subject my principles and practices to a strict scrutiny,
because I began to be doubtful of some of them.
But I was convinced that, as a rational creature, simply considered,
without a Divine Instructor, I was not competent to the undertaking.
I clearly perceived that all right understanding in spiritual concerns,
must proceed from the immediate revelation of the Holy Spirit,
and that we could not come to the knowledge of God,
nor of anything relating to his kingdom, without it.

This belief was very different from that held by the people I made profession with,
so that I had no assistance from them.
On the contrary, their conversation, their preaching, and their books, were against me.
I had no outward help but the Bible,
and that I could not understand without Divine assistance.
There were no people with whom I was acquainted who
believed in the Light of Christ within as I did,
so that I had none to look to for instruction in any difficulty, but to Him.
But, being very desirous to know the truth in all things,
I made application to Him whom I believe to be the only Teacher of his people,
and as I waited upon Him for instruction, my understanding was gradually enlightened,
so as to perceive many errors in my former creed,
and to discover the Truth in opposition to the doctrines of my education.

That which stood most in my way, and appeared to be a grievous hardship to mankind,
as well as a great dishonour to a just and righteous God,
was their doctrine of unconditional election and reprobation; which would,
according to their apprehension of it,
shut out the chief part of mankind from all hope of mercy,
as they believed they were the Lord`'s only people,
and that but few of others were within the pale of election.
Yet I believe there were some amongst them who had a more extensive charity.
I was much concerned on this subject, and being earnestly desirous to discover the truth,
it pleased the Lord to open my understanding,
clearly to perceive the error of this doctrine; and I was enabled to believe that Christ,
who "`gave Himself a ransom for all,`" would "`have all men to be saved,
and come to the knowledge of the Truth.`"

I rejoiced in this discovery,
and when I was fully convinced of my former error on this subject, I proposed,
for the consideration of one of my fellow students,
whether we had not been mistaken in that point of belief.
We reasoned on the question many times,
until he was almost convinced that we had been in an error on this subject.
He did not then know that my sentiments were different from his own,
but supposed that I proposed the question only for the sake of argument,
and to hear what could be said for and against it.
I purposely hid my real belief from him,
apprehending it not prudent at that time to discover my genuine sentiments.

By the time we were willing to close the debate on that subject,
I had something new to propose, and as strange as new to my opponent.
When we were at leisure from our studies, we entered into debate upon it; and so,
from time to time, we reasoned the point till we were willing to leave it.
Thus, as things opened to my view, and my mind became clear in any point of doctrine,
in opposition to my former belief, I proposed it for his consideration;
and so we reasoned upon it as long as we thought expedient.
Thus we proceeded from time to time, debating on divers points of doctrine,
until my opponent was partly convinced of the truths I advanced,
and became satisfied that I believed in the doctrines I produced for his consideration.
But, as I thought it not a proper time to make my opinions public,
I advised him not to expose them at present; to which he consented.
We spent our leisure time for two or three years, in discussing religious subjects,
new to him; and I was but recently convinced of the truth of them.

I had before this period heard of a people called Quakers,
but was unacquainted with any of them.
As I had never seen any of their writings, I knew not what doctrines they held,
but ascribe all my knowledge in divine things to
the inward manifestation of grace and truth,
the teaching of the Holy Spirit.
It was Christ, the Light of the world, the Life of men, who opened to me the Scriptures,
and gave me a discerning of their meaning; and,
as I was faithful and obedient to the pointings of Truth,
I was favoured with further and clearer discoveries thereof.
In this state I felt desirous that others should come to be acquainted with it,
and continued to give to my fellow student, aforementioned,
my views on the various subjects that presented.
We reasoned on them, as they were brought under consideration,
until we had discussed the principal disputable points of doctrine.
I do not remember that we omitted anything that
Robert Barclay had treated as a doctrinal point,
although, at that time, I had not seen any of his writings, nor ever heard of them,
as I remember.

I have mentioned these things to show that, according to Christ`'s declaration,
"`If any man do his will he shall know of his doctrine, whether it be of God;`"^
footnote:[John 7:17.]
and that "`we need not that any man teach us,
but as the anointing teacheth us of all things.`"
Though we had debated all those points, as before related, yet, at leisure hours,
we again discussed them, and became much of one sentiment on the various subjects,
as will appear when I come to relate the particulars of our final separation.

By this time I had some view of a false ministry and a false worship,
which had been introduced into almost all the churches
of professing Christians with which I was acquainted;
but my sight in these two particulars was not so clear
as it was in many others which we had debated.
Although I perceived a defect in the ministry,
yet I did not then see that it was altogether wrong,
nor did I then know that it was wholly of the "`letter that killeth;`"
but afterwards I obtained a clearer sight and knowledge thereof.
At this time I thought as a child, and understood as a child,
with regard to these subjects.
And this was also my state respecting divine worship.
I did not clearly perceive that all worship performed in the will of the creature,
and without the immediate assistance of the Holy Spirit,
was truly will-worship and idolatry.
But in process of time I clearly perceived that this was the case.
After our minds were satisfied on these points,
I first met with Barclay`'s [.book-title]#Apology.#--But I must
now leave my classmate and our discussions,
and go back a little.

When I had been at college about a year, the rector, or chief ruler,
sent for me to his house in order to converse with me
concerning those reports that had been circulated,
of my being a heretic.
After I had, at his request, seated myself by him, he told me he had a desire to hear,
from my own mouth, an account of my state: adding,
that it was not from any dissatisfaction in his own mind concerning me,
for he was well pleased with my conduct since I became one of their members;
that he believed the reports were chiefly owing to misapprehension, ignorance,
and ill-will; and that he wished to know from me the grounds of them.
This was the substance of his communication.
I replied, that if he would be pleased to have patience with me,
I would give him a plain account, and be as brief as I well might, to be intelligible.
I gave a relation of my first setting out on my religious journey, of my travels,
exercises, and experience, to that day, which took up about an hour and a half,
as I supposed.
He was all this time very quiet and attentive, not giving me the least interruption.
I thought he listened with much satisfaction.
When I had concluded we sat silent for some time.
He seemed to be so much affected that he could not easily speak.
After recovering, he said: "`Ferris,
I bless God for giving you eyes to see what few see.`"
He said nothing more to me,
except just to inform me that he was well satisfied with that opportunity;
and so he dismissed me.

I do not know that I concealed from him any of
the principles I held at the time he referred to,
when I was called a heretic,
but I did not unfold to him all my views at the time I was speaking,
being sensible he could not bear it.
He was a sincere professor, and a lover of good men,
and afterwards showed a kind regard for me,
saying more in my favour than I apprehend I deserved,
although not more than he believed to be true.
And this was the case with many others whose expectations of
my future usefulness had by some means been raised,
in consequence of which I was much esteemed by the most worthy class of people;
but being kept humble and low in my mind, and seeing my own weakness and infirmities,
I was preserved from the snares of popularity, although they made my trials the greater,
as will appear in the proper place.

After this interview with the rector, I resumed my studies,
which I pursued with diligence,
being desirous to be found in the way of my duty in every respect,
that a blessing might attend my undertaking.
I was careful of my thoughts, words, and actions,
endeavouring to be exemplary and serviceable to all about me.

I now became increasingly thoughtful on religious subjects.
The doctrines I had been taught, and the way of worship in which I had been educated,
were subjects of anxious concern.
I was desirous to ascertain whether they would bear a strict scrutiny.
On trial I found them defective;
and hence arose the many debates I had with my class-mate, as before related.

About the middle of the last year of my residence at the college,
I met with Barclay`'s [.book-title]#Apology;# and after reading it I let my class mate also peruse it,
with whom I had before discussed the doctrines there treated of.
He read the work attentively, and made little or no objection to it;
but told me Barclay`'s arguments were unanswerable.
Several other thoughtful scholars to whom I lent the book, after they had read it,
made the same acknowledgment,
with very little objection or opposition to the reasoning of its author.

I continued at the college until near the time for taking my degrees; and,
being convinced of the errors of my education relating to the doctrines we held,
and the worship we performed,
I apprehended it was time to consider what was best for me to do;
and being favoured to see that a qualification or commission
derived from man was not sufficient for the gospel ministry,
I concluded not to take their degrees, nor depend upon their authority.

Although I agreed with Barclay on doctrinal subjects,
yet l knew not that I could join with the Quakers,
or any other people with which I was acquainted.
I still continued a member of the Presbyterian society; attended their meetings,
and partook of their bread and wine.
But I was not free to sing with them, not having been, for some time before,
in a condition to sing: besides, it did not appear to me an acceptable sacrifice,
or any thing like divine worship,
for a mixed multitude to sing that of which they knew nothing by experience.
My exercise of mind daily increased,
for now the time was near at hand in which I must leave them.
This was a day of trial; for, although at the commencement of my religious progress,
I had forsaken all the youthful delights and vanities with which I had been diverted,
and had been enabled to trample them all under my feet,
expecting never again to encounter such difficulties,
yet now I found that self was not sufficiently mortified in me.
To be brought down from the pinnacle of honour, to be esteemed a fool,
be trampled under foot by high and low, rich and poor, learned and unlearned,
was hard to bear.
As I observed before, I had been much esteemed; though, as I was sensible,
more than I deserved.
I knew the people had undue expectations of my future usefulness,
and that if I left the college, as I thought it my duty to do, my credit would sink,
and my honours be laid in the dust; and then, instead of being caressed and exalted,
I must be neglected and despised.

But I had other difficulties to encounter.
My father looked forward with hope that I should be an honour to him and his family.
He had promised to set me out in the world in
the best manner his circumstances would admit.
I knew that if I were obedient to my convictions of duty,
he would regard it as a disgrace to my family and connections,
and would be more likely to turn me out of his house, than in any way to assist me.
Besides, I had heard of a vacancy for a minister,
and that the people were waiting for me to occupy it.
The congregation was numerous,
a larger salary was offered than any I knew of in that part of the country,
and I was informed that the rulers of the college had been consulted on the occasion.

Here, if I complied with my sense of duty,
I must "`take up the cross,`" and turn out unprovided for into the world;
for I had very little property of my own, none to expect from my father,
and no salary to support me.
Many would regard me as the off-scouring of all things, fit for nothing.

I laboured under a lively sense of all these difficulties.
Poverty and disgrace stared me in the face; and,
as I had none but the Lord to whom I could make known my distress and discouragements,
nor any other of whom to ask counsel, I cried to Him incessantly for wisdom, strength,
and fortitude, that I might be favoured with a clear discovery of my duty,
and enabled faithfully to obey Him in all things.

At this time my trials and difficulties were so numerous,
that I was ready to conclude with Job, that I should "`die in my nest.`"
I feared I should never be able to resign all my interest, honour, and credit,
in the world; submit to a state of poverty; and incur the disgrace of a reputed heretic.
These difficulties were presented to my view,
and magnified to the highest degree that any one can imagine.
In the height of my distress I entered my closet, or study,
and thus poured out my complaint before the Lord: "`O Lord!
I know not what to do, in this day of deep distress and anxiety of soul.
I am not sufficiently clear respecting my duty,
in the undertaking and execution of an affair of so much importance.
All that I have in this world that is valuable, and my everlasting happiness also,
are now at stake.`"

My present situation appeared so important, that if I mistook my course,
and took a wrong direction, all might be lost forever.
If I should be led by a spirit of error and confusion,
I might offend my Maker and my fellow creatures, forever remain in a dark wilderness,
and never be restored to favour with God or good men.

Darkness prevailed over me so far at that time,
that I seemed to be placed in the situation of John the Baptist,
when he sent two of his disciples to inquire of Christ, "`Art Thou He that should come,
or look we for another?`" --I was almost ready to despair,
and to conclude that I was altogether wrong in
proposing to take a step so contrary to reason,
as this now appeared to be.
Thus I poured forth my complaint, and mourned before the Lord.
I had none to depend upon but Him,
nor any other of whom to ask counsel in my distressed circumstances.
My dependance was wholly on Him for wisdom and direction,
in this trying and afflicting situation.

It is difficult to conceive, and not in my power to express,
the anxiety of my mind in this proving season;
for everything valuable seemed in danger of being totally lost.
Nevertheless, I cried to the Lord for help; and covenanted with Him,
that if He would be pleased to direct me in the way which would be safe for me to pursue,
manifest his will therein, and afford me assistance to perform my duties,
I would resign all to his disposal, obey his will, no longer reason with flesh and blood,
but trust to his providence for support and credit in the world,
and for everything else He might deem best and most convenient for me.
For I was now clearly convinced, that if I did not resign everything,
when it was evidently manifested to be my duty, I had nothing to expect but death,
as to my spiritual condition.

Whilst I was thus bemoaning my condition before the Lord; waiting upon Him for direction,
with ardent prayers for his assistance and wisdom to guide me in the right way,
He was graciously pleased to show me that He was
about to bring the Church out of the wilderness,
or wandering state, in which she had long been destitute of the true Leader.
And He made it clearly known to me that it was his will I should go forth,
and be an instrument in his hand for the accomplishment of this design.

As soon as I was satisfied on these points, I reasoned not with flesh and blood,
but immediately gave up to the heavenly vision.
I then went to the chief ruler of the college, and obtained his permission to go home;
but I told no one my reasons for this procedure.

This was a trying time.
I was about to take an important step.
Like Gideon, I was desirous to "`turn the fleece;`" to wait in retirement for wisdom,
maturely to consider this weighty undertaking, which now pressed heavily on my mind.
After staying at home about three weeks, the will of my Divine Master,
relating to my removal from college, was satisfactorily manifested.
Without making known my purpose, I returned to the college and settled my affairs,
in order to leave it.
Whilst I was preparing to depart,
a report was spread among the scholars that I was turned Quaker,
and was going to leave them.
Yet I did not hear that any of them uttered a hard or railing word against me.
The rector, Elisha Williams, took an opportunity to converse with me.
He was very moderate, but said he was sorry for my conclusion; that, heretofore,
he had entertained a good opinion of me,
and an expectation that I should be useful in my day, but now his hopes were,
in great measure, frustrated.
We had much conversation on the subject; he signified he did not give me up for lost.
He appeared serious, and we parted good friends.

As the time for my departure drew near, being wholly resigned to the Lord`'s will,
the cloud was removed from my tabernacle, my sight was clear, my courage returned,
and the mountains, whose tops so lately appeared to reach the clouds,
were all laid as level as a plain; the sea was driven back,
so that there was nothing to interrupt my passage.
I went over all, as on dry land, and not a dog was suffered to move a tongue against me.
Then was my soul filled with living praise, thanksgiving, and rejoicing in the Lord,
who had triumphed gloriously.
He was my strength, my song, and my salvation.
The deeps covered my enemies, they sank to the bottom as a stone.
The right hand of the Lord was glorious in power; and I sang his praises,
for He was worthy, having done great things for me.

Before I left college, I told the rector of my intentions,
and that I did not know that I should return, but if I should change my mind,
and wish to take a degree, if it would be permitted,
perhaps I might come back for that purpose; if I should conclude not to return,
I would write to him, and give my reasons for such conclusion.
He replied, and told me I should be welcome to a degree;
and that it would give them pleasure to grant me one.

While I was preparing for my journey, my class-mate, before mentioned,
being desirous to ride one day with me, obtained permission.
The rector told him, that I might, perhaps, instil bad principles into him,
and lead him astray.
To which my friend replied,
"`I have lived a great part of the time since I came to the college with him,
and I believe he has done me no harm, but contrariwise.`"
Then, having bidden them all farewell, we departed.

I thought it a favour that one of my fellows who was in good credit,
and esteemed none of the least in the college,
should be willing so far to take up the cross, as to accompany me,
who was deemed a heretic, a Quaker, or they knew not what;
but feeling a degree of love for me,
it made him fearless of shame or any disgrace that might ensue.

As we rode along, we discussed all the doctrines which we had formerly debated,
and he appeared almost as much convinced of the truth of my sentiments as I was.
Near night, when we were about to separate, he said: "`Ferris,
I believe you are right in leaving the college.
I believe your principles are sound and good; but I do not see, at present,
that I am called to do as you have done.
If, at any time hereafter, I should see it to be my duty to follow your example,
I purpose to have no will of my own, but submit to and obey the will of my Master.`"
We bade each other farewell, and I saw him no more;
but I afterwards heard that to follow my example was a cross too heavy for him to bear.
He took to preaching for a living among the Presbyterians, and never left them,
to my knowledge.

After I had parted with my companion, I went on to New-Milford,
where my parents and relations resided.
About three weeks afterwards, I went to a Yearly Meeting of the people called Quakers,
on Long Island, in order to discover whether they were a living people or not,
for a living people I wished to find.
I had thought for several years before that there ought to be such a people,
a people who had life in them, and abounded in love to each other,
as did the primitive Christians; a people who knew they had passed from death unto life,
by their love to the brethren.
Here I gathered strength, and was more confirmed that I was right in leaving the college;
for I found a living, humble people, full of love and good works,
such an one as I had never seen before.
I rejoiced to find that which I had been seeking,
and soon owned them to be of the Lord`'s people, and of the true church of Christ,
according to his own description of it, where he says,
"`By this shall all men know that ye are my disciples, if ye love one another.`"
I also found they held and believed the same doctrines,
the truth of which had been manifested to me immediately by the Holy Spirit;
being the same that Robert Barclay had laid down and well defended in his [.book-title]#Apology.#

Before I had read this work,
I did not know there was a people on earth who believed and lived in the Truth,
as described by Barclay; but here I found a numerous society who held the same truths,
and lived an humble, self denying life, becoming the character of Christians.
I was indubitably satisfied that their worship was in spirit and in truth,
and they such worshippers as the Father sought and owned.
I was convinced, beyond a doubt,
that they preached the Gospel in the demonstration of the Spirit;
and Divine authority was felt to attend their ministry.
They were not like the scribes, to whom I had been listening all my life,
who had neither commission nor authority, except that which was received from man;
being such as the Lord never sent,
and therefore could not profit the people they professed to teach.
I now clearly saw the difference between man-made ministers,
and those whom the Lord qualifies and sends into his harvest field;
the difference between the wheat and the chaff; and it was marvellous to me,
to reflect how long I had sat under a formal, dry, and lifeless ministry.

At the meeting before mentioned, there were several eminent ministers from Europe,
both male and female.
I there heard women preach the gospel, in the Divine authority of Truth,
far exceeding all the learned rabbis I had known.
This was not so strange to me as it might have been to others, for I had before seen,
by the immediate manifestation of grace and truth, that women, as well as men,
might be clothed with gospel power; and that daughters as well as sons,
under the gospel dispensation,
were to have the Spirit poured upon them that they might prophesy:
and though I had never before heard a woman preach,
yet I now rejoiced to see the prophecy fulfilled.

After I returned home from the Yearly Meeting,
I wrote a letter to the rector of the college,
informing him that I had deter mined not to return; and that I could not, with freedom,
take any authority that man could give.
I also informed him, that since I left them,
I had heard women preach the gospel far better than any learned man I had ever heard.
