== Chapter III.

[.chapter-synopsis]
* His proceedings after leaving College
* His joining the Society
* His marriage and settlement at Wilmington in 1737

Having now left the college,
and separated myself from the people among whom I had been educated,
I saw great cause of thankfulness to the Author of all good;
who had revealed to me the errors of my youth,
and the falsity of the doctrines imbibed in my education;
who had made known to me his truth and people; so that I had no doubts remaining.
It now became my principal concern that I might be enabled to walk in the truth,
and witness the Holy Spirit to lead me on my way.

In this state I admired the boundless goodness, the infinite kindness,
and tender mercy of a gracious God, in effecting my late deliverance;
especially when I considered how tempestuous were the seas,
and how the billows rolled over me;
how the mountains of opposition raised their lofty heads to stop my passage; and again,
in a short time, how the winds and seas were hushed and still;
and how the mountains became a perfect plain,
I truly found as great cause to sing upon the banks of deliverance, as Israel did of old,
when they had passed through the sea on dry ground;
and had turned about and seen their enemies dead on the shore.
I rejoiced in the Lord, and sang praises to Him, who had done marvellous things for me;
who had made me acquainted with his blessed truth;
and at length gave me ability to trample the world, and all its riches, honours,
and pleasures, under my feet; to submit to the cross of Christ;
and be willing to be accounted a fool of all men.
For which favours I felt myself under great obligations to my gracious Benefactor.

I will now return to a former part of my narrative,
and give some account of my reception by my relatives.
After I had parted with my class-mate, on my way home from college,
I heard that my father had received intelligence of my intentions,
and was much dissatisfied with my proceedings; saying,
"`If the accounts I have heard be true, I desire he may never come to my house again.`"
Being informed of this, I went to my brother's. After some days I went to see my father.
He would not speak to me; but turned and passed away without taking notice of me.
In a few days afterwards I went a second time; but he still, refused to speak to me.

After a few days I went the third time, and met him at the door,
and asked after his health; at the same time pulling off my hat;
(for at that time I was not convinced of the necessity
of bearing a testimony against hat honour;) he replied,
he was not very well, and passed away.
I then went into the house, and my father returning,
we sat down and entered into conversation.
He said he had heard I had left the college and turned Quaker.
In reply I told him, it had been my endeavour for some years past,
to follow my divine Leader, and that I still endeavoured to attend to the same Guide,
and follow whithersoever he might lead me;
that I apprehended he had led me to leave the college,
and forsake the way of my education;
and it was possible that the same Guide might some time
lead me to join the people called Quakers;
but that, as yet, I knew but little of them.

After some time spent in conversation of this kind,
my father queried what need there was to forsake the way of my education;
"`For,`" said he, "`the Lord has favoured you, and been with you in the Presbyterian way:
so that if you continue to fear and serve Him in that way, you may do well; and will,
no doubt, end in peace.`"
I answered, it was true I had been much favoured under my former profession;
the Lord had been near me, and his living presence with me.
He had led and guided me by his good Spirit,
and had revealed his will to me far beyond any thing I had deserved,
or could have expected;
and I still desired to follow that Teacher who had never led me astray;
but had brought me, step by step, from one degree of experience to another,
until I was obliged to leave the college,
and bear a testimony against the formal profession I had made;
and thus He had led me to the present time.

Thus we conversed for some hours; my father raising objections to the Quakers,
and my joining with them.
But, through divine assistance,
(with which I think I was favoured,) I was enabled fully to answer all his objections;
so that he was willing to leave the subject; and became moderate, and, apparently,
more easy in his mind.
From that time, during the remainder of his life, although he had many opportunities,
he never entered into any arguments with me on religious subjects;
but was always kind and affectionate.
I thought he concluded I might do well in the way he found me, and so remained satisfied.

After I had been some time at home,
new objections arose in my mind against a compliance
with the customs of those among whom I resided;
such as bowing and scraping; putting off the hat; saying, "`Your servant, sir, madam,
etc.`" and against using the ungrammatical,
corrupt language of "`you`" to a single person.
Although, in past years, I had known various exercises,
and thought I had learned many hard lessons,
yet I found much in me that required mortification,
and that I yet had many things to learn.
To refuse the use of the plural language to a single person,
although it seemed a small matter, yet I found it hard to submit to.
I was convinced,
that the common mode of speaking in the plural number to a single person,
was a violation of the rules of grammar, and unscriptural.
I also believed the pride of man had introduced the custom,
yet I thought it was not necessary to make myself ridiculous
to all about me for a matter of so small importance.
So long, therefore,
as no necessity was laid upon me to take up the cross in that respect,
I continued to use the language of my education.
Yet I used compliments sparingly; because the disuse of them was not so observable.
However,
it was not long before I found it my duty to say
"`Thee`" and "`Thou`" to every individual.

Nevertheless,
I found an inclination or temptation so to turn
the conversation as to shun this mode of speech;
yet this did not afford peace.
Small as the matter appeared,
I could not be easy without being entirely faithful in every respect;
and my duty in this particular being clearly manifested,
I reasoned no longer with flesh and blood; but submitted to the requiring.
It was a rule with me to do nothing of this kind by imitation; but,
when any thing was required of me, to submit; and thus I obtained peace.

About this time, several scholars coming from the college,
invited me to accompany them on a visit to the minister in our settlement;
and accordingly I went with them.
We walked with our hats under our arms, and so entered the house.
Just as we were about to depart,
I was required to bear a testimony against the hat honour.
So I rose, put on my hat, went to the priest, and bade him farewell,
without putting my hand to it, or bowing my body.
This being the first time I had refused these compliments, it was a close trial;
and it appeared remarkable, that it should be required of me at such a time,
and in such company: but neither the priest nor my companions took notice of it,
so as to make any remark.
My obedience afforded me great peace; and,
by yielding to these inward motions of the sure Guide, in small things,
I gained strength;
and was more and more confirmed that I was right in making such a change.

I now began to lay aside some of the superfluities of my dress,
and to appear like a Quaker;
believing it was required of me not to hide myself in any respect;
but boldly to bear testimony to the truth, so far as it was clearly manifested to me.
I did not then wonder that people admired at our folly,
(as they think it to be,) in making ourselves a laughing-stock and by-word,
by our singularities; because,
so it appeared to me but a short time before I was obliged to submit to it.
I loved the honour and esteem of men, as well as others; and would have enjoyed it,
if I could have had it with peace of mind;
but that is not allowed in the school of Christ,
where nothing will do without self-denial and taking up the daily cross; and if,
on our part, there be a full submission in every respect, I can say, from experience,
that our peace will flow as a river.

Having left the college without taking a degree,
it was probable I should have no salary to depend on for subsistence.
I had disobliged my father, and of course had nothing to expect from him;
and I had but little of my own to support me.
And now, being come to the twenty-fifth year of my age,
I began to think it necessary to use some endeavours to obtain a livelihood.
I had for several years before this period thought I should go to reside in Pennsylvania;
and this prospect now opened so clearly,
that I was inclined to believe it was my duty to go there.
I accordingly made ready and went, in company with three ministering friends from Europe,
then on a religious visit to America.
We arrived in Philadelphia about the middle of the sixth month, 1733.

Here ends that part of my narrative which was written in my youth in the Latin language.

As I observed before, I arrived in Philadelphia in 1733.
I concluded that if I could establish myself in business that would be likely to answer,
I would, for some time, make the city my residence.
After the Yearly Meeting was over, and I had become a little acquainted with Friends,
and known among them, I proposed to open a school,
to teach the Latin and Greek languages.
But, as I was a stranger,
and those children that were intended to be taught
these languages were mostly entered in other schools,
I was doubtful whether I should be able to get a sufficient number of such scholars.
I therefore agreed to teach English also; and, in time, I had a school, of both sexes,
sufficiently large for my support.

Being a stranger, I consequently met with trials and difficulties.
For a while my school was small, and not likely to support me;
but I endeavoured to be resigned,
and repose with confidence in an all-sufficient Providence,
from whom I had often received help in times of great trial.
My difficulties were increased by the low state of my funds.
The weather was now beginning to grow cold.
It was customary for the teacher to find wood for fuel,
and for the scholars to pay a proportion of the expense,
when they paid for their quarter's tuition; and as I had but few scholars,
and no money yet due, and not ten shillings of my own remaining,
I was very thoughtful how to procure wood.
No one knew the state of my purse; nor did I desire to make it known;
and this I should do if I attempted to borrow.
I, therefore, omitted to buy, as long as I well could.
I did not like to ask for credit; and if I did,
it was doubtful whether I should obtain it; so that I was closely tried.
But, while I was under this exercise,
the weather was more moderate than usual at that season.

After I had been sufficiently tried,
to prove my faith and confidence in Divine Providence, a Friend came into my school,
and privately gave me twenty shillings;^
footnote:[Twenty shillings in 1733, would, probably,
be equally valuable with ten dollars (forty-five shillings) in 1825.]
which, he said, had been sent by a Friend, who did not wish to be known as the donor.
For this unexpected favour, I was thankful to the Lord, whose mercies endure for ever.
Having now the means, I soon purchased some wood; and the weather, in a short time,
be coming colder, I had a renewed sense of the kindness of Providence,
who had so seasonably relieved me.
But afterwards, when my stock of wood was nearly exhausted,
I was brought into the same difficulty and trial, as before;
and as much needed a renewal of my faith.
I strove to be quiet,
and to have my dependence placed on Him who fed a great
multitude with a few loaves and little fishes;
and just as I began to suffer,
another twenty shilling bill was privately presented to me by an unknown hand;
but I received it as coming from the Lord, who knew all my difficulties.

Thus was I again relieved; and never afterwards received any thing more in this way;
nor did I ever need it, as I was sufficiently supplied by the proceeds of my business.
This was a confirmation to me, that I had been assisted by a watchful Providence,
who knows all states and conditions, both internal and external;
and is able and willing to turn the hearts of his people,
and constrain them to help the needy; as, formerly,
he sent the ravens to feed the prophet.

I have made these few remarks for the sake of those who may be in similar circumstances,
and stand in need of faith and confidence in the care of Divine Providence,
over his dependent people;
desiring they may afford them encouragement to put their trust wholly in the Lord,
and not faint in the day of inward or outward trials.

After I had been about six months in Philadelphia,
I requested to be taken into membership with Friends; and was, accordingly, received.
Some time after I had joined the Society, I began to think of settling myself,
and to marry, when the way should appear without obstruction;
which was not then the case.
I considered marriage to be the most important concern in this life.
"`Marriage,`" said the apostle, "`is honourable in all.`"
I concluded he meant that it was honourable to all who married from pure motives,
to the right person, and in the proper way and time, as Divine Providence should direct.
I believed it best for most men to marry; and that there was, for each man,
one woman that would suit him better than any other.
It appears to me essential that all men should seek for wisdom, and wait for it,
to guide them in this important undertaking; because no man, without divine assistance,
is able to discover who is the right person for him to marry;
but the Creator of both can and will direct him.
And why, in such an important concern, should we not seek for counsel,
as well as in matters of minor consequence? There is, moreover,
greater danger of erring in this than in some other concerns,
from our being too impatient to wait for the pointings of divine wisdom; lest,
by so doing, we might lose some supposed benefit.
It is common for young people to think and say, "`I would not marry such a person;
for certain reasons: such as the want of beauty, wit, education,`" etc.;
and to affirm that they could not love such an one;
but we may err by an over-hasty conclusion,
as well as by any other neglect of our true Guide.

I now propose to give some hints of my own proceedings in this concern.
Near the place of my residence there lived a comely young woman, of a good,
reputable family; educated in plainness; favoured with good natural talents;
and in good circumstances.
Every view of the case was favourable to my wishes.

By some hints I had received,
it appeared probable that my addresses would be agreeable to her;
and some of my best friends urged the attempt.
From inattention to my heavenly Guide, I took the hint from man;
and following my own inclination, I moved without asking my Divine Master's advice:
I went to spend an evening with the young woman,
if I should find it agreeable when there.
She and her mother were sitting together; and no other person present.
They received me in a friendly manner;
but I think I had not chatted with them more than half an hour, before I heard something,
like a still small voice, saying to me,
"`Seekest thou great things for thyself?--seek them not.`"
This language pierced me like a sword to the heart.
It so filled me with confusion, that I was unfit for any further conversation.
I endeavoured to conceal my disorder; and soon took my leave, without opening,
to either the mother or her daughter, the subject which had led me to visit them.
And I afterwards had substantial reason to think it was
well for me that I had failed in this enterprise.

I was so confused and benumbed by this adventure,
that I did not recover my usual state for several months;
though I could not suddenly see that my error was acting without permission;
but began to suppose that I should never be suffered to marry;
and should have to pass my life without a companion or a home.
I endeavoured to be resigned to this view; supposing it was the Lord's wiłł; but,
for several months, it was a severe trial.
At length I was brought to submit, and say, "`Amen.`"
This simple account of my visit to that young woman, is designed as a warning to others;
that they may shun the snare into which I was so near falling.

I shall now relate another of my movements, with respect to marriage,
which I believe was a right one; as it terminated to lasting satisfaction.
It may appear strange to some, as if I married in the cross; and, I suppose,
few will be inclined to follow my example.
Yet, if the Divine Teacher of truth and righteousness be attended to,
it may be the lot of some.
After I had been much mortified and humbled, under a sense of my former mis-step, I went,
one day, to a Friend's house to dine.
As I sat at the table, I observed a young woman sitting opposite to me,
whom I did not remember ever to have seen before.
My attention, at that time, being otherwise engaged, I took very little notice of her;
but a language very quietly, and very pleasantly, passed through my mind, on this wise:
"`If thou wilt marry that young woman, thou shalt be happy with her.`"
There was such a degree of divine virtue attending the intimation,
that it removed all doubt concerning its origin and Author.
I took a view of her, and thought she was a goodly person; but,
as we moved from the table, I perceived she was lame.
The cause of her lameness I knew not;
but was displeased that I should have a cripple allotted to me.
It was clear to me, beyond all doubt, that the language I had heard was from heaven;
but I presumptuously thought I would rather choose for myself.

The next day the subject was calmly presented to my mind, like a query:
"`Why shouldst thou despise her for her lameness it may be no fault of hers.
Thou art favoured with sound limbs, and a capacity for active exertion;
and would it not be kind and benevolent in thee, to bear a part of her infirmity,
and to sympathize with her? She may be affectionate and kind to thee;
and thou shalt be happy in a compliance with thy duty.`"
Notwithstanding all this, I continued to reason against these convictions;
alleging that it was more than I could bear.
The enemy of my happiness was busily engaged,
in raising arguments against a compliance with my duty.
Suggesting that it was an unreasonable thing that I should be united to a lame wife;
and that every one who knew me would admire at my folly.^
footnote:[The author's person was rather uncommonly good,
and it is probable he might have thought too highly of personal excellence.]

Thus, from day to day, and week to week, I reasoned against it; until, at length,
my kind Benefactor, in a loving and benevolent manner, opened to my view, that,
if I were left to choose for myself, and to take a wife to please my fancy,
she might be an affliction to me all the days of my life; and lead me astray,
so as to endanger my future happiness.
Or she might fall into vicious practices; not withstanding that,
at the time of her marriage, she might be apparently virtuous; it was, therefore,
unsafe to trust to my natural understanding.
On the other hand, here was a companion provided for me by Unerring Wisdom;
so that I might rely with safety on the choice.
Still I was unwilling to submit.
But heavenly kindness followed me,
in order to convince me that it would be best to comply, and no longer resist the truth.

At length it pleased the Lord, once more, clearly to show me that if I would submit,
it should not only tend to my own happiness,
but that a blessing should rest on my posterity.
This was so great a favour, and manifested so much divine regard,
that I no longer resisted; but concluded to pay the young woman a visit,
and open the subject for her consideration; but,
after I had laid my proposition before her, I still had hopes that I might be excused;
and only visited her occasionally.
During this time, for several months, I endured great trials and afflictions,
before I was fully resigned.
But, after divine Goodness had prevailed over my rebellious nature,
all things relating to my marriage wore a pleasant aspect.
The young woman appeared beautiful;
and I was prepared to receive her as a gift from heaven, fully as good as I deserved.
We waited about six months for my parents`' consent, from New-England,
(a conveyance by letter being at that time difficult to obtain,) and
accomplished our marriage on the thirteenth of the ninth month,
1735, in the city of Philadelphia.

It is now forty years since we married; and I can truly say that I never repented of it,
but have always regarded our union as a proof of divine kindness.
I am fully sensible there was no woman on earth so suitable for me as she was.
And all those things which were shown me, as the consequence of my submission,
are punctually fulfilled.
A blessing has rested on me and my posterity.
I have lived to see my children arrived to years of understanding,
favoured with a knowledge of the truth;
(which is the greatest of all blessings;) and some of them, beyond all doubt,
are landed in eternal felicity.
I have been blessed with plenty; and, above all, with peace.
I am, therefore, satisfied and thankful to my gracious Benefactor,
for his kindness to me in this concern, as well as for all his other favours;
who am not deserving of the least of all the mercies and all
the truth which He has shown to his unworthy servant.

I have given this relation so circumstantially,
with a view to show how incapable we are to see things in their true light,
until we are truly humbled, and brought into subjection to the divine will;
and how unsafe it is for poor, frail, short-sighted creatures,
to reject so safe a counsellor, and trust to their own wisdom,
in concerns of such importance.
Therefore, let all seek that "`wisdom that cometh from above; which is pure, peaceable,
gentle, and easy to be entreated.`"

Whilst I was proceeding in my concerns relating to marriage,
I was also thoughtful concerning the proper place to reside;
and the business I should engage in for support.
I had now kept a school nearly four years;
and had partly concluded to resign that employment,
on account of the confinement necessarily attending it;
and having heard of a new settlement then making in the county of New-Castle,
(since called Wilmington,) I was inclined to see it; and thought, if it pleased me,
I might perhaps settle there.
It had been a subject of frequent consideration; but when I mentioned it to my wife,
she appeared unwilling to leave Philadelphia; as she had lived there nearly all her life,
and her relations resided in that city.
But William Shipley and his wife, from Springfield, in Chester county, proposing,
in a short time, to settle in Wilmington, I went with them to see the place.
It pleased me so well that I rented a lot of ground there; and, on my return,
told my wife what I had done.
She thought we should never make use of it.

In those days, by various trials, exercises, and afflictions,
I was reduced to a very low state.
My natural powers seemed to be so much weakened,
that I could not judge what course to take, or how to proceed, in my temporal concerns,
as I had formerly done, or as others could do; so that I saw no way for me to move,
with prudence or safety, without immediate direction from the Fountain of Wisdom.
And I may say, with humility of heart, and thankfulness to the God of all mercies,
that as I sought for it, and waited for direction, I sought Him not in vain.
I waited upon Him; not daring to move until He appeared to point out the way;
and He failed not to show me what step I should take, and when to take it,
in a wonderful manner.
It was marvellous in my eyes, that a poor worm should be thus favoured;
and I should not venture to mention how particularly I was led,
if I did not believe it to be my duty.

Observing how ignorant and thoughtless mankind is, in general, of a Divine Instructor,
especially in their temporal concerns,
(supposing themselves sufficient to manage the affairs of this life,
and therefore not expecting or seeking for superior
intelligence,) I feel anxious for an amendment,
where we are out of the true order;
and shall now give some hints of my own experience in relation to this subject.

As before mentioned, I had taken a lot of ground in Wilmington;
but as yet it was not clear to me that it would be best for us to reside there;
and my wife seeming unwilling to think of it,
great were the trials that attended my mind.

To move from one place to another, in our own time and will,
I believe is a matter of serious consequence.
A change of residence appears to me next in importance to marriage; and, therefore,
requires the same Divine Wisdom to direct us aright.
We may be qualified for service in one place; and, by removing to a distance,
unless we are directed by unerring counsel,
the designs of Providence respecting us may be frustrated; and our usefulness lessened.

Under these considerations I was reduced very low in mind;
being sensible of my own inability rightly to direct my course.
I was full of cares and fears;
and so humbled that I was willing to be or do
any thing that was pleasing to my dear Master,
so that I might be favoured with a knowledge of his will;
even if it were to take my axe or spade, and labour for the support of my small family.
After many months spent in anxious solicitude on this subject,
light gradually arose on my mind.
Sometimes it appeared best to move; and again the prospect seemed dark and cloudy; but,
at length, the prospect of removing to the new settlement of which I have spoken,
and of keeping a store for the sale of goods there, appeared so clear,
that I applied for a house convenient for this purpose, if I should conclude to remove.
Yet, although I had proceeded so far, I was under a daily care lest I should be mistaken,
and take a wrong step;
so as to bring a reproach on the profession of Truth I had made to the world.

While I was under this concern, I was taken ill with the small-pox;
and had it pretty severely.
When on the recovery, as I sat by the fire one evening, in company with my wife,
I received a letter from the owner of the house, of which I had the refusal.
He informed me that I must write to him the next morning,
and say whether I would take it or not;
as another person had determined to take possession of it.
There was no other house in the settlement which would
be at all suitable for my intended business.
This brought me into a close trial.
After I had read the letter to my wife, we sat silent for some time.
At length she cheerfully said, "`Well, let us go.`"
Which I rejoiced to hear; although, at that time, the prospect was enveloped in darkness.
I made, her but little reply; and being weak in body, and dark in mind, I retired to bed.
After I had lain some time, revolving the difficulties of my situation,
with fervent desires for divine direction, I went to sleep; and had a good night's rest;
which I had not enjoyed before, during that illness.
About the dawn of the day, it seemed as if I heard a clear and intelligible language,
saying to me: "`Go, and prosper; fear not; the cattle on a thousand hills are mine;
and I give them to whom I please.
Behold!
I will be with thee.`"
Immediately all my doubts vanished; I saw, with sufficient clearness,
that I might go with safety, and hope for a competent subsistence.
These circumstances I related to my wife, and told her of my prospects,
which afforded her encouragement.
I then arose, and wrote to the owner of the house,
informing him that I had concluded to take it;
and that I hoped to move at the time proposed.
Accordingly I removed to it, with my family, in the third month, 1737;
taking with me some goods for my store.

After our removal, the minds of the people, both in town^
footnote:[The town at that time contained about forty houses.]
and country, were inclined to deal with us;
and we soon sold the few goods we brought from the city.
I then had occasion to think of "`the cattle on a thousand hills,`" with
heart-felt gratitude to Him who keepeth covenant with his children,
and whose mercies fail not.
He neither slumbereth nor sleepeth; but His watchful eye regardeth his depending people,
as I have ever found.
