== Chapter IV.

[.chapter-synopsis]
* His sentiments on Trade
* He reverts back to the time of his convincement, and relates his trials and conflicts respecting engaging in the work of the Ministry
* His first appearance, in the year 1755

I will now give some of my views on the subject of business,
lawful for Christians to engage in.
Children may be apprenticed to trades which are inconsistent with a Christian profession.
For instance, some are taught to make instruments of war;
which they who believe in the peaceable doctrines of Christ cannot lawfully engage in.
There are several other callings which I believe Christians cannot consistently follow.

It is the duty of those who profess to follow Christ, the Light of the world,
to consider whether the business in which they engage, is agreeable to his will; and,
if a doubt arise respecting its propriety, to ask counsel, and wait for wisdom,
to know how to proceed.
I was educated under a supposition that human learning was sufficient
to qualify me to teach people the way to peace and happiness.

This was clearly revealed to me to be a mistake, and I had not the shadow of a doubt,
that they who trusted in human learning, to qualify them for the gospel ministry,
were entirely wrong.
In consequence of this conviction, I employed myself in teaching a school,
which I believe was right for me at that time.
And when I purposed to enter into another business,
being convinced I ought to ask counsel of the great Counsellor,
I did not run in my own will, and choose my own ways.
I was satisfied, that, as we were blessed with a divine Teacher,
it was our duty to follow his directions, in temporal, as well as spiritual concerns,
especially in movements of importance.
And when I believed it would be right to keep a store,
I was desirous that I might proceed in the business under the
direction of Him who seemed willing to teach me.

Not having served an apprenticeship to the mercantile business,
I was ignorant of the quality and prices of goods; it was, therefore,
probable that I should be under some difficulty in these respects.
But, as I kept near my Guide, He never failed to direct me safely,
both in my religious progress and my worldly concerns.
The advantages arising from a faithful attention to the leading of the Holy Spirit,
are very great; far greater than my tongue or pen can express,
even in the management of our temporal affairs.
And, I believe, all real Christians might have their understandings enlightened,
and their eyes anointed, clearly to see how to proceed in all concerns of importance,
provided the pure fear of the Lord prevailed in their hearts;
and an humble dependance and full confidence in the
all-sufficient Helper were steadily maintained.
I speak from experience.
He has been my Instructor in a very peculiar manner, much more so than I have mentioned,
or than I can describe;
and I am far from supposing that I have been more deserving than others.
Christ said: "`Ask and ye shall receive.`"
I asked for his direction and assistance, and He helped me, and I found the promise true.

I believe it is consistent with the Divine will,
that all should have their hope and dependance more fully placed in his almighty power,
and that they should wait for instruction from Him, in all their undertakings.
Thus their understandings would be enlarged, their ideas would be clear, and,
having submitted all to the disposal of Divine Providence,
who had directed their proceedings, they would go forward without any anxious cares,
or distracting thoughts, respecting events.
I know this to my comfort.
So far as I have conformed to this view, a blessing has attended my undertakings,
besides the blessings of peace and an easy mind.

But, before I leave this subject, I will observe,
that I did not always so closely attend to my blessed Instructor,
as I ought to have done: of which I will relate some instances.
It was the practice of shop-keepers to sell rum,
and I was told that if I did not conform to it,
I need not expect to do any business of importance.
So, without waiting for direction, I fell into the practice,
and followed it for several years, until it became a subject of uneasiness to me.
I found many used that article to the injury both of body and mind.
Some spent their estates to procure it,
and thus brought themselves and their families into want and distress;
which gave me trouble of mind.
But, being unwilling to lose the profits of this branch of business,
I adopted an expedient to soothe my pain; which was,
to refuse selling it to such as I thought would make an evil use of it.
But this did not answer my expectations,
for they would send for it by those who were not suspected.
At length I was made willing to relinquish the profits on this article,
and trust to Providence for the result.
I ceased to sell it, which afforded me peace, and made no great diminution of my business.

It was also customary, in those days, for Friends, as well as others,
to sell many superfluous articles; such as gay calicoes, flowered ribbands,
and other fine things, which we, as a society, did not allow our families to wear;
and which it was not consistent with our profession to encourage in others.
With these views, I endeavoured to lay aside all such superfluities,
and to deal in such articles only, as were really useful.
I was told that if I refused to sell such goods, I might quit my business; but,
as I did it from a sense of duty, I was not sensible that I sustained any loss by it.

After I had been in business several years, and had increased in wealth,
three or four of my fellow-townsmen concluded to build a vessel,
and trade to the West Indies; and, without consulting my kind Instructor,
I was prevailed upon to join them.
But being favoured, after some years, to see my error,
I withdrew from the concern as soon as possible,
and confined myself to the business of my store.
As I attended to this business,
I found I could not feel easy to sell my goods for as much as I could get for them,
as was the practice with many; but by selling them at a moderate profit,
I obtained peace of mind.

I am aware that many, and even some who make a high profession of religion,
will deem my remarks on business, marriage, etc. unworthy of notice,
and be ready to smile at them, as the whims and notions of a distempered,
enthusiastic brain; because they have had no such experience.
Yet there may be others, who, having had some knowledge of this way,
will be glad of these remarks; for I am sure, beyond all doubt,
that what I have written is true, and well worthy of attention.^
footnote:[When we consider the present state of most religious professors,
it is no marvel they should reject the doctrine
of spiritual direction in secular concerns;
although it was plainly promised by Christ: "`When he the Spirit of Truth, is come,
He will guide you into all truth.`"
John 16:13.]

And if men were universally to attend to the direction
of Him who is come to lead us into all truth,
the wars and devastation now prevailing in our land
would not have existed.^
footnote:[The Revolutionary War.]

I will now recur to the time when I first joined the society of Friends.
After I was admitted into membership,
I diligently attended all our meetings for worship and discipline,
and greatly admired the beautiful order established in the society,
and the living gospel ministry with which we were favoured.
After I had been a member about one year, I was concerned to appear in the ministry,
and excite the careless to a consideration of their "`latter end.`"
I had passed through many vicissitudes and tribulations;
but when this concern was laid upon me,
it seemed heavier than anything I had ever had to bear.
I thought I could never be resigned to it.

When I was called out of the vanities of my youth,
and was obliged to submit to the cross of Christ,
to become a laughing-stock and a by-word to my companions and acquaintances;
I was so humbled, so mortified, and self so much abased,
I thought I could submit to any thing that might afterwards be required of me.
Again, when I passed through that great trial of leaving the college,
in the manner before related; to deny all the honours, friendships, pleasant connections,
and riches of the world, I concluded I should never again meet with so great a trial.
But I was mistaken.
This far exceeded all I had previously encountered.
I, however, submitted so far as to speak a few times in our meetings; and then,
through great fear that I should not be able to persevere, I was induced to be silent,
and postpone the performance of this duty until a more "`convenient
season,`" or more full manifestation of the Divine will.
I concluded, that if I should continue, for any considerable time,
to appear as a minister, and afterwards should be silent,
it would bring greater dishonour on my profession than
thus to cease at an early period of such a concern.
Sometimes I hoped that at a future meeting the trial would not be so severe; at others,
that more strength would be granted me.
Thus I reasoned, from month to month, and year to year, during seven years.
In all which time the concern was often so heavy,
that I sat and trembled through the time of meeting; and then went away full of sorrow,
trouble, and pain of heart.

For several years after this, I seldom felt this concern,
yet I was still sensible that I had a work of this kind to do,
and felt great pain in neglecting it.
I saw no way to obtain peace of mind, but by a submission to the cross,
and becoming willing to be accounted a fool; and this being a severe trial, I evaded it.
Sometimes I had a faint hope that I should yet obtain strength to proceed in the work;
at other times, I was almost in despair.
Thus I passed along for fifteen years,
during which time my error was manifested to me in various ways;
sometimes by the Holy Spirit, showing me that "`obedience is better than sacrifice,
and to hearken to the voice of the Lord than the fat of
rams;`"--sometimes by the ministry of his messengers;
and sometimes by dreams, etc.
Thus, in great mercy, the Lord followed me as He did Ephraim of old, saying:
"`How shall I give thee up, O Ephraim!`"

One night I dreamed that I saw a large, spacious building in an unfinished state;
and the master-builder, who appeared an excellent person, came to me,
as I stood at a distance, and desired me to go and take a view of it, to which I agreed;
and as we were surveying it, and examining the particular parts,
I observed that among the many pillars erected for the support of the building,
there was one lacking.
I queried of him what was the cause of that vacancy.
He replied, it was left for me,
and that I was specially designed and prepared for the place;
and showed me how I fitted it, like as a mortise is fitted to its tenon.
So that I saw in my dream that all he said was true.
But, notwithstanding all this, I objected to my capacity and fitness to fill the vacancy;
and was, therefore, unwilling to occupy it.
He endeavoured, by the most convincing reasons, to remove all my objections,
and to demonstrate that I was fitted for the place.
He further told me, that they had not another prepared for it,
and that the building would be retarded if I did not comply with the design.

After he had reasoned with me a long time, and I still refused,
he appeared to be grieved,
and told me it was a great pity that I should be
rendered useless in the house by my own obstinacy.
And then added, "`But it must not be so, for if thou wilt not be a pillar,
thou shalt be a plank for the floor.`"
He then showed me how I might be flatted and prepared for that purpose.
But I refused that place also;
on the ground that it looked too diminutive to be a
plank to be trod upon by all who came into the house.
At this the master was troubled, seeing I would accept no place that was offered me: but,
after a long debate, he concluded to leave the propositions he had made,
for my further consideration; and so we parted.

The next day I was at a meeting on Long Island,
and a concern came heavily upon me to say something that was presented to my mind.
The burden of the word was weighty, and more difficult to remove than usual;
but I contended with it, and, at length, refused to comply.
I was then in company with two women Friends.
The following night one of them dreamed that she
saw me sitting by a pleasant stream of water,
before me a table was spread with all manner of dainties; but I was chained,
so that I could not reach any of them: at which she was troubled,
and asked the master of the feast,
why I was deprived of the liberty to partake of the good things on the table.
He answered, that the time had been, when, on certain conditions,
I might have enjoyed them to the full, but that I had refused the terms,
and therefore was now justly deprived of them.
She inquired of him whether this must always be my case.
He answered, perhaps not; that if I would yet submit, and comply with the terms,
it was not too late to partake of all the good things she saw.
The interpretation of this dream, and of mine the night before, was easy and plain.
They rested on my mind for several years, as cause of humbling instruction,
and excitement to future care, diligence, and obedience.

The next day,
as we were travelling towards a town where we
intended to have a meeting the following day,
we were informed that a people, called the New-lights,
were to have a meeting there the same day; and that we might, probably,
get there at the time their meeting was sitting.
As soon as I heard it, I thought the word of the Lord passed through me, saying:
"`Thou must go to that meeting.`"
I knew not the object,
but supposed it might be to bear a testimony
against their errors in worship and practice,
and to proclaim the truths of the gospel in their hearing.
I rode on without speaking to my companions, but the concern remained weightily with me.
I endeavoured, as usual, to get from under it; saying to my Master,
"`I am in no wise qualified for the service;`" and desiring
that He would send by those who were fitted for such a work;
or, as Moses said, "`by whom He would send,`" so that I might be excused.

Whilst I was struggling to evade this service, one of the women turned to me and said:
"`Why canst thou not go to this meeting of the New-lights,
and proclaim to them the truth,
as our Friends did formerly?`" Her speech added
fuel to the fire that was burning within me.
I thought it came with Divine authority, but I made her no reply,
having before as much as I could well bear.
I, how ever, felt an engagement to press forward;
and when we arrived at the house where we intended to tarry for refreshment,
being under great exercise of mind, I walked backward and forward across the room.
The friend who had spoken to me on the road, I observed, was under great exercise also.
I walked and reasoned as long as I well could.
At length the power of opposition was overcome, and I was obliged to submit.
I then observed to the friend, "`I believe I must go to that meeting.`"
She replied, "`I believe so also.`"
The landlord, hearing what was said, proposed to go with me; and I accepted of his offer.
So being pressed in spirit to make haste, we set out, and coming to the meeting-house,
I stepped on the door-sill, to go in, and at that instant the meeting broke up.
I then stepped aside, and stood still, in retirement of mind; waiting to know my duty.
The people rushed out of the house, and I found my mind relieved of concern;
so I was easy to return, without further service.
I believed the will to act, in this case, was accepted for the deed,
and I returned in peace.

Thus was I shown that my divine Master was able to
bring me to a state of submission to his holy will,
and I then concluded that, if He would excuse me from such a trying service,
I would no longer refuse to speak among those of my own persuasion.

But after all this, I proceeded with a heavy heart,
being convinced that my work was neglected.
It was several years, after this occurrence, before I fully submitted to the Divine will;
in all which time I went on lamenting my unfaithfulness.
Sometimes I had a hope, as it were, against hope,
that I should obtain a victory over that slavish fear which had so long enthralled me.
At other times I was ready to conclude there was no cause to hope for deliverance from it.
Yet, during this period, I was not wholly forsaken by my Divine Master,
but was enabled to perform, I hope with acceptance, some services for Him;
such as warning the drunkard, the profane swearer, and the liar,
of the evil of their ways, and advising them to repent.
Sometimes, during this period,
I was also concerned to accompany Friends who were
engaged to visit religious meetings in distant places;
in yielding to which I found peace.
Yet, when abroad on such services, and my call to the ministry was brought into view,
the sense of my neglect sunk my spirits; and pain of heart attended me.
Thus I spent more than twenty years!

Although, as has been mentioned, I had been many times invited,
and had received indubitable evidence of the Divine will,
both immediately and instrumentally, so that every doubt was removed from my mind;
yet the fear of man, the fear of missing my way, the fear of doing more harm than good,
prevailed against me,
so that I thought I should never be able to submit to the Divine will concerning me.
But, towards the termination of the aforesaid time, I felt more lively;
and a concern to appear in the ministry revived.

Being from home, at a meeting, I was concerned to say something to the people; but,
according to my usual custom, I postponed it till a more convenient season.
On this account I left the meeting in great heaviness and sorrow, for my disobedience.

On the following night, I dreamed that I saw two generals drawing up their armies,
in order for battle.
Each captain had his men in order, ready to obey the command of their general,
and stood at their head, waiting for orders to march,
and stand in the engagement where he should command them.
One of the generals came to a captain, who stood near me, and said to him,
"`You are a valiant man, and skilful in the art of war,
therefore march into the right wing of the army, and in front of the battle.`"
But the captain objected to the post assigned him, and pleaded his unfitness for it;
saying, "`It is a place of danger, and requires a man better qualified for such a post.`"
The general answered, that he was well qualified for the place allotted him,
and that if he took it, he might, by his skill and valour,
do eminent service for his king and country, and gain great honour;
which would be a means of promoting him to places of higher trust.
He, however, desired to be excused,
and could not be persuaded to take the post assigned him.
I stood by, and heard all the general`'s arguments to persuade him to comply,
until I was filled with indignation at the captain`'s obstinacy;
especially as the general had absolute authority to command,
and yet was so kind as to use entreaty and persuasion.
I then said to the general, "`It is my judgment,
that this captain is not worthy of the place assigned him,
since he refuses to serve his king and country according to his capacity,
and rejects the honour and promotion he might obtain.
Were I in the general`'s place, I would set him in the rear of the army,
where he will have less opportunity of promotion,
and may lose his life as well as in the front.`"
To this the general replied, "`The decision is just,
and in the rear he shall stand;`" where he was accordingly stationed.

I awoke from my sleep in great distress;
under a sense of the just judgment which (like David) I had passed on myself.
From this time, during several months, I was on the brink of despair,
concluding I was wholly unworthy to stand in front; and, therefore,
should be placed in the rear, to be killed in obscurity.
After a time of great anxiety and distress of mind,
the Lord was graciously pleased to look upon me with compassion,
and again offered to make me a pillar in his house;
and I felt a renewed concern to appear in public for his Name, and in the cause of Truth.

In the year 1755,
being in company with Comfort Hoag (afterwards Comfort Collins) and her companion,
from New-England, then on a religious visit to Friends in this part of the country,
I attended a meeting with them, in which I felt a concern to speak to the assembly; but,
as usual, evaded it.
After meeting, Comfort said to me: "`David,
why didst thou not preach today?`" I smiled at the query,
seeming to wonder that she should ask such a question;
and endeavoured to appear innocent and ignorant of any concern of that kind.
As she knew nothing of me but what she had felt,
(having never before seen or heard of me,) she said no more.
On the following day a similar concern came upon me, and I evaded it as before.
After meeting, Comfort again said to me: "`David,
why didst thou not preach today?`" I endeavoured to pass it by as before,
but she said it was not worthwhile to evade it,
for she was assured that I ought to have preached that day;
and that I had almost spoiled her meeting by refraining, which had hindered her service.
When I found I could not conceal my faults, I confessed the whole,
and told her I had been for more than twenty years in that practice;
and then gave her a history of my life from the beginning down to that day.
She admired that Divine kindness was yet manifested to ward me in such a manner,
seeing I had so long rebelled against it.
And then gave me suitable caution and advice.

The following day, being at meeting, I again felt a concern to speak to the people,
but endeavoured to evade it.
A man of some note was sitting before me, and increased my reluctance to speak.
I supposed he would not be present at the next meeting,
and then I would obey the call of the Lord to that service.
Thus I spent the greater part of an hour.
At length my Divine Master, the great Master Builder, thus addressed me:
"`Why dost thou still delay,
desiring to be excused until a more convenient season?
There never will be a better time than this;
I have waited on thee above twenty years; I have clearly made known to thee my will,
so that all occasion of doubt has been removed, yet thou hast refused to submit,
until thy day is far spent, and if thou dost not speedily comply with my commands,
it will be too late; thy opportunity will be lost.`"
I then clearly saw that if I were forsaken, and left to myself,
the consequence would be death and darkness for ever!
At the sight of the horrible pit that yawned for me, if I continued in disobedience,
my body trembled like an aspen leaf, and my soul was humbled within me!
Then I said, "`Lord! here am I; make of me what Thou wouldst have me to be;
leave me not in displeasure, I beseech Thee.`"

All my power to resist was then suspended,
I forgot the great man that had been in my way
and was raised on my feet I scarcely knew how,
and expressed, in a clear and distinct manner, what was on my mind.
When I had taken my seat, Comfort Hoag rose, and had an open,
favourable opportunity to speak to the assembly.
After meeting she told me that, during the time we had sat in silence,
her whole concern was on my account;
that her anxiety for my deliverance from that bondage was such,
that she was willing to offer up her natural life to the Lord,
if it might be a means to bring me forth in the ministry; and that,
on her making the offering, I rose to speak.
On which her anxiety for me was removed,
and her mind filled with concern for the people present.^
footnote:[Comfort Hoag (afterwards Comfort Collins) survived this journey many years,
and died when more than one hundred years of age.
She was a lively minister till near her end.]

At that time I was made a real Quaker,
and was not ashamed to be seen trembling before the Lord.
Under a sense of so great and merciful a deliverance, I saw and felt ample cause for it.
It was with me as with Israel of old, when the Lord caused their captivity to return;
saying He would build them as at the first;
and they should fear and tremble for all his goodness,
and for all the prosperity He would procure for them.
My soul rejoiced in the Lord, and I magnified his excellent Name,
who is worthy of all honour, glory, and renown, for ever.

It appeared to me wonderful,
that I should thus be lifted out of this horrible pit of my own digging;
and I was so absorbed in the love and mercy of my heavenly Benefactor,
that I was filled with thankfulness and praise, attended with a desire that, in future,
I might diligently watch and wait for the pointing of his holy finger,
to every service He might be pleased to allot me;
that henceforth no opportunity might be lost of manifesting my gratitude,
by obedience to his will.
My feelings were like those of a prisoner who had been long in bonds,
and was set at liberty.

This appearance in the public ministry was in the year 1755;
and in the forty-eighth year of my age.
After which it was never so great a cross to speak in meetings as it had been before.
At many times, during my long silence, I had a sight that if I were obedient to my duty,
I might be made a useful member of the church, and as a pillar in God`'s house; but,
having so long rebelled,
I now had no reason to expect that I should be so useful as I might have been,
had I rendered early obedience to the heavenly call.
However, it appeared necessary, if little were committed to my trust,
to be faithful to that little.
Sometimes I had a hope of being useful to my fellow creatures;
at other times I was left to myself,
and humbled under a sense of my own inability to do anything to the honour of God,
or the help of others.
